/* ============================================================
   LESDATA — leerlijnen en vragenbanken
   Dit bestand bevat alle inhoud van de cursus, los van de app-logica
   in index.html. Wordt vóór het hoofdscript geladen, dus COURSES, SOON,
   QUIZZES en ZINS zijn daar gewoon beschikbaar.

   Er zijn twee leerlijnen:
     • Woordjes   — COURSES + QUIZZES (woordenschat, zie hieronder).
     • Zinsopbouw 1 — ZINS (zinsstructuur: WIE → DOET → WAT → WAAR → WANNEER,
                    zie het commentaar boven de ZINS-lijst onderaan dit bestand).
     • Zinsopbouw 2 — ZINS2 (zelfde theorie als leerlijn 1, maar andere zinnen;
                    zie het commentaar boven de ZINS2-lijst onderaan dit bestand).

   Een WOORDJES-les toevoegen? Zet een regel in COURSES (tag "feat" optioneel)
   en voeg een blok toe in QUIZZES met hetzelfde lesnummer. De structuur:
     t = vraag, o = antwoorden, c = index van het juiste antwoord (0=eerste),
     e = uitleg, tag = vraagtype, tip = hint (optioneel, meestal een
     makkelijke voorbeeldzin met het woord).
   Optioneel (laten weg = niets te zien):
     img    = afbeelding bij de vraag (URL of pad, bijv. "images/trein.jpg").
     tipImg = afbeelding in het tip-vakje (handig om een woord in beeld uit te
              leggen). Voorbeeld: {tag:"…", t:"…", o:[…], c:0, e:"…",
              tip:"Kijk naar het plaatje.", tipImg:"images/hamer.jpg"}.
   Leerlingen kunnen elk Nederlands woord ook laten uitspreken (🔊-knop);
   dat werkt automatisch, daar hoef je niets voor in te stellen.
   Controleer met: node scripts/validate-lessons.js
   ============================================================ */
const COURSES = [
  {n:"1", t:"Nieuwe buren & verhuizen", desc:"Woorden uit thema 1: buren, huur, wijk, verhuizen."},
  {n:"2", t:"Marktplaats & spullen", desc:"Woorden over kopen, verkopen en spullen in huis."},
  {n:"3", t:"Op het station", desc:"Woorden over de trein, berichten en vertraging."},
  {n:"4", t:"Reizen & OV-chipkaart", desc:"Woorden over pinnen, opladen en veilig reizen."},
  {n:"5", t:"Contact met de buren", desc:"Woorden over gasten, feest en samenwonen.", bookmark:true},
  {n:"6", t:"Het huis beschrijven", desc:"Woorden over vorm, maat en materiaal."},
  {n:"7", t:"Grote mix: les 1 t/m 6", desc:"Alle thema's door elkaar. Herhaal en test wat je geleerd hebt.", feat:true},
];
/* SOON = 'binnenkort'-onderwerpen zonder eigen les. Leeg = geen placeholderkaarten. */
const SOON = [];

/* ---------------- vragenbanken ---------------- */
const QUIZZES = {
  "1":{ title:"Nieuwe buren & verhuizen", sub:"Lees het woord. Kies het goede antwoord. Bij elke vraag zie je ook het Turkse woord (Türkçe) als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent het woord <span class='m'>de buren</span>?", o:["komşular","misafir","aile","arkadaş"], c:0,
      e:"<b>de buren</b> = komşular. Dat zijn de mensen die naast je wonen.",
      tip:"In een zin: <i>De <b>buren</b> wonen naast ons huis.</i> Het gaat dus over de mensen die naast je wonen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de buurman</span>?", o:["komşu (erkek)","misafir","aile","arkadaş"], c:0,
      e:"<b>de buurman</b> = (erkek) komşu. De man die naast je woont. De vrouw is <i>de buurvrouw</i>.",
      tip:"In een zin: <i>De <b>buurman</b> is een man die naast je woont.</i> Denk aan 'man' in het woord."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verhuizen</span>?", o:["taşınmak","temizlemek","satın almak","aramak"], c:0,
      e:"<b>verhuizen</b> = taşınmak. Je gaat in een ander huis wonen. Voorbeeld: <i>Wij verhuizen naar een nieuw huis.</i>",
      tip:"In een zin: <i>Wij <b>verhuizen</b> naar een nieuw huis.</i> Je gaat dus ergens anders wonen."},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>komşular</span> (de mensen naast je)?", o:["de buren","de gast","de wijk","de hulp"], c:0,
      e:"komşular = <b>de buren</b>. 'de gast' = misafir, 'de wijk' = mahalle.",
      tip:"Denk aan de mensen die vlak naast jou wonen. Welk Nederlands woord hoort daarbij?"},
    {tag:"de of het", t:"Wat is goed: <span class='m'>___ huis</span>?", o:["het huis","de huis","een huizen","dat huizen"], c:0,
      e:"Het is <b>het huis</b>. Dit woord krijgt 'het'. Deze woorden leer je uit je hoofd.",
      tip:"Zeg hardop: '... huis'. Dit woord hoort bij de kleinere groep 'het'-woorden.", tipImg:"images/huis.svg"},
    {tag:"de of het", t:"Wat is goed: <span class='m'>___ wijk</span> (mahalle)?", o:["de wijk","het wijk","een wijken","die wijken"], c:0,
      e:"Het is <b>de wijk</b> = mahalle. De meeste woorden krijgen 'de'.",
      tip:"Een buurt in de stad. De meeste woorden krijgen 'de' — welk lidwoord past hier?"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de huur</span>?", o:["kira","fiyat","ev","oda"], c:0,
      e:"<b>de huur</b> = kira. Dat is het geld dat je elke maand voor je huis betaalt.",
      tip:"In een zin: <i>Elke maand betaal ik de <b>huur</b> voor mijn huis.</i> Het gaat om geld voor je woning."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het adres</span>?", o:["adres","isim","şehir","numara"], c:0,
      e:"<b>het adres</b> = adres. Straat, huisnummer en plaats waar je woont. Let op: het is 'het adres'.",
      tip:"In een zin: <i>Op de brief staat mijn <b>adres</b>: straat, nummer en plaats.</i>"},
    {tag:"Werkwoord", t:"Welke zin is goed? <span class='m'>Gisteren ___ wij naar een nieuw huis. (verhuizen)</span>", o:["verhuisden","verhuizen","verhuis","verhuist"], c:0,
      e:"Verleden tijd: <b>verhuisden</b>. Nu = wij verhuizen, gisteren = wij verhuisden.",
      tip:"'Gisteren' betekent verleden tijd. Nu = wij verhuizen; welke vorm past bij gisteren?"},
  ]},
  "2":{ title:"Marktplaats & spullen", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de advertentie</span>?", o:["reklam / ilan","fiyat","dükkan","hediye"], c:0,
      e:"<b>de advertentie</b> = ilan/reklam. Bijvoorbeeld op Marktplaats zet je een advertentie om iets te verkopen.",
      tip:"In een zin: <i>Ik zet een <b>advertentie</b> op Marktplaats om mijn bank te verkopen.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verkopen</span>?", o:["satmak","almak","bakmak","aramak"], c:0,
      e:"<b>verkopen</b> = satmak. Het tegenovergestelde is 'kopen' (satın almak).",
      tip:"In een zin: <i>Ik wil mijn oude fiets <b>verkopen</b> voor 20 euro.</i> Het is het tegenovergestelde van kopen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>bieden</span>?", o:["teklif vermek","ödemek","göndermek","sormak"], c:0,
      e:"<b>bieden</b> = teklif vermek. Voorbeeld: <i>Ik bied 10 euro voor de stoel.</i>",
      tip:"In een zin: <i>Ik <b>bied</b> 10 euro voor de stoel.</i> Je zegt hoeveel je wilt betalen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>hout</span> (houten)?", o:["tahta / ahşap","cam","demir","yün"], c:0,
      e:"<b>hout</b> = tahta. Een houten tafel = ahşap masa.",
      tip:"In een zin: <i>De tafel is van <b>hout</b>.</i> Denk aan een boom.", tipImg:"images/hout.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>wol</span> (wollen)?", o:["yün","pamuk","deri","plastik"], c:0,
      e:"<b>wol</b> = yün. Een wollen trui = yün kazak.",
      tip:"In een zin: <i>Een <b>wollen</b> trui is lekker warm.</i> Het komt van een schaap.", tipImg:"images/wol.svg"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>halı</span>?", o:["het kleed","de spiegel","de knop","de hamer"], c:0,
      e:"halı = <b>het kleed</b>. Let op: het is 'het kleed'.",
      tip:"Denk aan iets zachts dat op de vloer ligt. Welk Nederlands woord hoort daarbij?", tipImg:"images/kleed.svg"},
    {tag:"Tegenstelling", t:"Wat past bij <span class='m'>rond</span> (yuvarlak)? Kies het tegenovergestelde.", o:["vierkant","breed","zwaar","laag"], c:0,
      e:"<b>rond</b> = yuvarlak, <b>vierkant</b> = kare. Dat zijn tegenovergestelde vormen.",
      tip:"Een bal is rond. Wat is de vorm met vier rechte hoeken, zoals een doos?"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opsturen</span>?", o:["göndermek","almak","yırtmak","saklamak"], c:0,
      e:"<b>opsturen</b> = göndermek. Voorbeeld: <i>Ik stuur het pakket op met de post.</i>",
      tip:"In een zin: <i>Ik <b>stuur</b> het pakket <b>op</b> met de post.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>zwaar</span>?", o:["ağır","hafif","geniş","dar"], c:0,
      e:"<b>zwaar</b> = ağır. Het tegenovergestelde is 'licht' (hafif).",
      tip:"In een zin: <i>De doos is heel <b>zwaar</b>, ik kan hem bijna niet tillen.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>breed</span>?", o:["geniş","dar","yüksek","alçak"], c:0,
      e:"<b>breed</b> = geniş. Het tegenovergestelde is 'smal' (dar).",
      tip:"In een zin: <i>De kast is te <b>breed</b> voor deze muur.</i> Het gaat over de breedte."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>tweedehands</span>?", o:["ikinci el","yeni","pahalı","bedava"], c:0,
      e:"<b>tweedehands</b> = ikinci el. Iemand heeft het al gebruikt. Voorbeeld: <i>Ik koop een tweedehands bank.</i>",
      tip:"In een zin: <i>Ik koop een <b>tweedehands</b> bank; iemand gebruikte hem al.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>ayna</span>?", o:["de spiegel","het kleed","de hamer","de knop"], c:0,
      e:"ayna = <b>de spiegel</b>. In de spiegel zie je jezelf. 'het kleed' = halı, 'de hamer' = çekiç.",
      tip:"Denk aan het glas waarin je jezelf ziet. Welk Nederlands woord hoort daarbij?", tipImg:"images/spiegel.svg"},
  ]},
  "3":{ title:"Op het station", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de automaat</span>?", o:["makine / otomat","tren","bilet","kapı"], c:0,
      e:"<b>de automaat</b> = makine/otomat. Bij de automaat op het station koop je een kaartje.",
      tip:"In een zin: <i>Bij de <b>automaat</b> koop ik een kaartje.</i> Het is een machine.", tipImg:"images/automaat.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het bericht</span>?", o:["mesaj","ses","kağıt","resim"], c:0,
      e:"<b>het bericht</b> = mesaj. Voorbeeld: <i>Ik krijg een bericht op mijn telefoon.</i>",
      tip:"In een zin: <i>Ik krijg een <b>bericht</b> op mijn telefoon.</i> Zoals een appje of sms."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>handig</span>?", o:["kullanışlı / pratik","zor","pahalı","tehlikeli"], c:0,
      e:"<b>handig</b> = kullanışlı. Iets dat makkelijk is om te gebruiken.",
      tip:"In een zin: <i>Deze app is heel <b>handig</b>, hij helpt me snel.</i> Dus makkelijk in gebruik."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het lawaai</span>?", o:["gürültü","müzik","sessizlik","haber"], c:0,
      e:"<b>het lawaai</b> = gürültü. Veel hard geluid.",
      tip:"In een zin: <i>Er is veel <b>lawaai</b> op straat; ik kan niets horen.</i> Veel hard geluid."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hulp</span>?", o:["yardım","soru","zaman","yol"], c:0,
      e:"<b>de hulp</b> = yardım. Werkwoord: helpen = yardım etmek.",
      tip:"In een zin: <i>Bedankt voor je <b>hulp</b>!</i> Denk aan het werkwoord 'helpen'."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>ergens</span>?", o:["bir yerde","hiçbir yerde","her zaman","şimdi"], c:0,
      e:"<b>ergens</b> = bir yerde. Voorbeeld: <i>Mijn kaartje ligt ergens in mijn tas.</i>",
      tip:"In een zin: <i>Mijn kaartje ligt <b>ergens</b> in mijn tas.</i> Op een plek, maar je weet niet precies waar."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de vertraging</span>?", o:["gecikme","varış","hız","durak"], c:0,
      e:"<b>de vertraging</b> = gecikme. De trein komt later dan normaal.",
      tip:"In een zin: <i>De trein heeft <b>vertraging</b> en komt tien minuten later.</i>", tipImg:"images/trein.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>op tijd</span>?", o:["zamanında","geç","erken","asla"], c:0,
      e:"<b>op tijd</b> = zamanında. Niet te laat en niet te vroeg.",
      tip:"In een zin: <i>De trein is <b>op tijd</b>: niet te laat en niet te vroeg.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>duidelijk</span>?", o:["açık (net anlaşılır)","zor","yavaş","sessiz"], c:0,
      e:"<b>duidelijk</b> = açık / net. Je snapt het meteen. Voorbeeld: <i>Het bericht op het bord is duidelijk.</i>",
      tip:"In een zin: <i>Het bord is <b>duidelijk</b>, ik snap het meteen.</i>"},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ bericht</span>", o:["het bericht","de bericht","een berichten","die berichten"], c:0,
      e:"Het is <b>het bericht</b>. Dit woord krijgt 'het'.",
      tip:"Zeg hardop: '... bericht'. Dit woord hoort bij de groep 'het'-woorden."},
  ]},
  "4":{ title:"Reizen & OV-chipkaart", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opladen</span>?", o:["şarj etmek","kapatmak","satmak","kırmak"], c:0,
      e:"<b>opladen</b> = şarj etmek. Je laadt je OV-chipkaart of je telefoon op.",
      tip:"In een zin: <i>Ik moet mijn OV-chipkaart <b>opladen</b> voordat ik reis.</i> Ook je telefoon doe je zo."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pinpas</span>?", o:["banka kartı","para","cüzdan","fatura"], c:0,
      e:"<b>de pinpas</b> = banka kartı. Hiermee betaal je in de winkel.",
      tip:"In een zin: <i>Ik betaal in de winkel met mijn <b>pinpas</b>.</i> Een kaart van de bank.", tipImg:"images/pinpas.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pincode</span>?", o:["pin kodu / şifre","adres","isim","numara"], c:0,
      e:"<b>de pincode</b> = pin kodu. De geheime cijfers van je pinpas.",
      tip:"In een zin: <i>Ik typ mijn geheime <b>pincode</b> in bij de automaat.</i> De cijfers van je pas."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het scherm</span>?", o:["ekran","tuş","kart","ses"], c:0,
      e:"<b>het scherm</b> = ekran. Bijvoorbeeld het scherm van de automaat of je telefoon.",
      tip:"In een zin: <i>Op het <b>scherm</b> van de automaat lees je de tekst.</i>", tipImg:"images/scherm.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>veilig</span>?", o:["güvenli","tehlikeli","hızlı","yavaş"], c:0,
      e:"<b>veilig</b> = güvenli. Het tegenovergestelde is 'gevaarlijk' (tehlikeli).",
      tip:"In een zin: <i>Bewaar je pincode <b>veilig</b>, dan kan niemand hem stelen.</i> Niet gevaarlijk."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de knop</span>?", o:["düğme / tuş","kapı","yol","ekran"], c:0,
      e:"<b>de knop</b> = düğme/tuş. Je drukt op de knop.",
      tip:"In een zin: <i>Druk op de groene <b>knop</b> om te beginnen.</i>", tipImg:"images/knop.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>drukken op</span>?", o:["basmak","çekmek","tutmak","atmak"], c:0,
      e:"<b>drukken op</b> = basmak. Voorbeeld: <i>Druk op de groene knop.</i>",
      tip:"In een zin: <i>Je moet met je vinger op de knop <b>drukken</b>.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>minimaal</span>?", o:["en az","en çok","bazen","hemen"], c:0,
      e:"<b>minimaal</b> = en az. Voorbeeld: <i>Je hebt minimaal 4 euro nodig.</i>",
      tip:"In een zin: <i>Je hebt <b>minimaal</b> 4 euro nodig: minder mag niet.</i> Dus 'ten minste'."},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ scherm</span>", o:["het scherm","de scherm","een schermen","dat schermen"], c:0,
      e:"Het is <b>het scherm</b>. Dit woord krijgt 'het'.",
      tip:"Zeg hardop: '... scherm'. Dit woord hoort bij de groep 'het'-woorden."},
  ]},
  "5":{ title:"Contact met de buren", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>boos</span>?", o:["kızgın","mutlu","yorgun","üzgün"], c:0,
      e:"<b>boos</b> = kızgın. Voorbeeld: <i>De buurman is boos om het lawaai.</i>",
      tip:"In een zin: <i>De buurman is <b>boos</b> om het lawaai.</i> Hij is niet blij."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de gast</span>?", o:["misafir","komşu","aile","çocuk"], c:0,
      e:"<b>de gast</b> = misafir. Iemand die bij je op bezoek komt.",
      tip:"In een zin: <i>Vanavond komt er een <b>gast</b> eten.</i> Iemand op bezoek."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>moe</span>?", o:["yorgun","kızgın","mutlu","hasta"], c:0,
      e:"<b>moe</b> = yorgun. Voorbeeld: <i>Ik ben moe na het verhuizen.</i>",
      tip:"In een zin: <i>Na het verhuizen ben ik heel <b>moe</b>.</i> Je wilt slapen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>overmorgen</span>?", o:["öbür gün","dün","bugün","her gün"], c:0,
      e:"<b>overmorgen</b> = öbür gün (yarından sonraki gün). Vandaag → morgen → overmorgen.",
      tip:"Denk aan: vandaag → morgen → <b>overmorgen</b>. Dus over twee dagen."},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>hard</span> (sert / yüksek sesli)?", o:["zacht","stil","boos","moe"], c:0,
      e:"<b>hard</b> ↔ <b>zacht</b> (yumuşak / hafif). 'zacht' betekent ook: niet luid.",
      tip:"Een kussen is niet hard, maar juist ...? Denk aan het tegenovergestelde."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>stil</span>?", o:["sessiz","gürültülü","hızlı","güvenli"], c:0,
      e:"<b>stil</b> = sessiz. Het tegenovergestelde van lawaai.",
      tip:"In een zin: <i>'s Nachts is het <b>stil</b> in de straat.</i> Geen geluid, geen lawaai."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de leeftijd</span>?", o:["yaş","isim","adres","boy"], c:0,
      e:"<b>de leeftijd</b> = yaş. Voorbeeld: <i>Wat is de leeftijd van je kind?</i>",
      tip:"In een zin: <i>Wat is de <b>leeftijd</b> van je kind?</i> Hoeveel jaar iemand is."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de verjaardag</span>?", o:["doğum günü","davetiye","tatil","bayram"], c:0,
      e:"<b>de verjaardag</b> = doğum günü. Op je verjaardag word je een jaar ouder.",
      tip:"In een zin: <i>Op mijn <b>verjaardag</b> word ik een jaar ouder.</i>", tipImg:"images/taart.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>oppassen</span>?", o:["göz kulak olmak","uyumak","oynamak","beklemek"], c:0,
      e:"<b>oppassen</b> = göz kulak olmak. Voorbeeld: <i>Ik pas op de kinderen van de buren.</i>",
      tip:"In een zin: <i>Ik <b>pas op</b> de kinderen van de buren.</i> Je let goed op ze."},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>davetiye</span>?", o:["de uitnodiging","de verjaardag","het gesprek","de gast"], c:0,
      e:"davetiye = <b>de uitnodiging</b>. Je krijgt een uitnodiging voor een feest. 'de verjaardag' = doğum günü.",
      tip:"Denk aan wat je krijgt als je naar een feest mag komen. Welk Nederlands woord hoort daarbij?"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vieren</span>?", o:["kutlamak","çalışmak","beklemek","taşınmak"], c:0,
      e:"<b>vieren</b> = kutlamak. Voorbeeld: <i>Wij vieren mijn verjaardag met de buren.</i>",
      tip:"In een zin: <i>Wij <b>vieren</b> mijn verjaardag met taart.</i> Iets leuks samen doen."},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ gesprek</span> (konuşma)", o:["het gesprek","de gesprek","een gesprekken","die gesprekken"], c:0,
      e:"Het is <b>het gesprek</b>. Dit woord krijgt 'het'.",
      tip:"Zeg hardop: '... gesprek'. Dit woord hoort bij de groep 'het'-woorden."},
  ]},
  "6":{ title:"Het huis beschrijven", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>modern</span>?", o:["modern / yeni tarz","eski","küçük","ucuz"], c:0,
      e:"<b>modern</b> = modern. Het tegenovergestelde is 'ouderwets' (eski).",
      tip:"In een zin: <i>Het huis is <b>modern</b>: nieuw en van deze tijd.</i> Niet ouderwets."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>ruim</span>?", o:["geniş / ferah","dar","karanlık","dolu"], c:0,
      e:"<b>ruim</b> = geniş/ferah. Er is veel plek. Voorbeeld: <i>Een ruime kamer.</i>",
      tip:"In een zin: <i>De kamer is lekker <b>ruim</b>: er is veel plek.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vierkant</span>?", o:["kare","yuvarlak","üçgen","uzun"], c:0,
      e:"<b>vierkant</b> = kare. Een vorm met vier gelijke kanten.",
      tip:"Denk aan een vorm met vier gelijke, rechte kanten, zoals een dobbelsteen.", tipImg:"images/vierkant.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de meter</span>?", o:["metre","kilo","litre","saat"], c:0,
      e:"<b>de meter</b> = metre. Je meet lengte in meters. 100 cm = 1 meter.",
      tip:"In een zin: <i>De kamer is drie <b>meter</b> breed.</i> 100 cm = 1 hiervan.", tipImg:"images/meter.svg"},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>laag</span> (alçak)?", o:["hoog","breed","rond","licht"], c:0,
      e:"<b>laag</b> = alçak, <b>hoog</b> = yüksek. Dat zijn tegenovergestelden.",
      tip:"Een tafel is laag, maar een flat is juist ...? Denk ver naar boven."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hamer</span>?", o:["çekiç","testere","vida","merdiven"], c:0,
      e:"<b>de hamer</b> = çekiç. Gereedschap om te timmeren.",
      tip:"In een zin: <i>Met een <b>hamer</b> sla ik een spijker in de muur.</i> Gereedschap.", tipImg:"images/hamer.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>licht</span>?", o:["hafif / aydınlık","ağır","karanlık","sıcak"], c:0,
      e:"<b>licht</b> heeft twee betekenissen: hafif (niet zwaar) én aydınlık/ışık. Tegenovergestelde van zwaar én van donker.",
      tip:"In een zin: <i>De tas is <b>licht</b> (niet zwaar) en de kamer is <b>licht</b> (niet donker).</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>rond</span>?", o:["yuvarlak","kare","düz","köşeli"], c:0,
      e:"<b>rond</b> = yuvarlak. Zoals een bal of een bord.",
      tip:"Denk aan de vorm van een bal of een bord: zonder hoeken.", tipImg:"images/rond.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>breed</span>?", o:["geniş","dar","yüksek","kısa"], c:0,
      e:"<b>breed</b> = geniş. Het tegenovergestelde is 'smal' (dar).",
      tip:"In een zin: <i>De kast is te <b>breed</b> voor deze muur.</i> Het gaat over de breedte."},
  ]},
  "7":{ title:"Grote mix: les 1 t/m 6", sub:"Alle thema's uit les 1 t/m 6 door elkaar. Türkçe woord staat erbij als hulp. Elke keer in andere volgorde.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent het woord <span class='m'>de buren</span>?", o:["komşular","misafir","aile","arkadaş"], c:0,
      e:"<b>de buren</b> = komşular. Dat zijn de mensen die naast je wonen.",
      tip:"In een zin: <i>De <b>buren</b> wonen naast ons huis.</i> Het gaat over de mensen die naast je wonen."},
    {tag:"Werkwoord", t:"Welke zin is goed? <span class='m'>Gisteren ___ wij naar een nieuw huis. (verhuizen)</span>", o:["verhuisden","verhuizen","verhuis","verhuist"], c:0,
      e:"Verleden tijd: <b>verhuisden</b>. Nu = wij verhuizen, gisteren = wij verhuisden.",
      tip:"'Gisteren' betekent verleden tijd. Nu = wij verhuizen; welke vorm past bij gisteren?"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verkopen</span>?", o:["satmak","almak","bakmak","aramak"], c:0,
      e:"<b>verkopen</b> = satmak. Het tegenovergestelde is 'kopen' (satın almak).",
      tip:"In een zin: <i>Ik wil mijn oude fiets <b>verkopen</b> voor 20 euro.</i> Het tegenovergestelde van kopen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>tweedehands</span>?", o:["ikinci el","yeni","pahalı","bedava"], c:0,
      e:"<b>tweedehands</b> = ikinci el. Iemand heeft het al gebruikt. Voorbeeld: <i>Ik koop een tweedehands bank.</i>",
      tip:"In een zin: <i>Ik koop een <b>tweedehands</b> bank; iemand gebruikte hem al.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>ayna</span>?", o:["de spiegel","het kleed","de hamer","de knop"], c:0,
      e:"ayna = <b>de spiegel</b>. In de spiegel zie je jezelf. 'het kleed' = halı, 'de hamer' = çekiç.",
      tip:"Denk aan het glas waarin je jezelf ziet. Welk Nederlands woord hoort daarbij?", tipImg:"images/spiegel.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de vertraging</span>?", o:["gecikme","varış","hız","durak"], c:0,
      e:"<b>de vertraging</b> = gecikme. De trein komt later dan normaal.",
      tip:"In een zin: <i>De trein heeft <b>vertraging</b> en komt tien minuten later.</i>", tipImg:"images/trein.svg"},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ bericht</span>", o:["het bericht","de bericht","een berichten","die berichten"], c:0,
      e:"Het is <b>het bericht</b>. Dit woord krijgt 'het'.",
      tip:"Zeg hardop: '... bericht'. Dit woord hoort bij de groep 'het'-woorden."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opladen</span>?", o:["şarj etmek","kapatmak","satmak","kırmak"], c:0,
      e:"<b>opladen</b> = şarj etmek. Je laadt je OV-chipkaart of je telefoon op.",
      tip:"In een zin: <i>Ik moet mijn OV-chipkaart <b>opladen</b> voordat ik reis.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pincode</span>?", o:["pin kodu / şifre","adres","isim","numara"], c:0,
      e:"<b>de pincode</b> = pin kodu. De geheime cijfers van je pinpas.",
      tip:"In een zin: <i>Ik typ mijn geheime <b>pincode</b> in bij de automaat.</i> De cijfers van je pas."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>veilig</span>?", o:["güvenli","tehlikeli","hızlı","yavaş"], c:0,
      e:"<b>veilig</b> = güvenli. Het tegenovergestelde is 'gevaarlijk' (tehlikeli).",
      tip:"In een zin: <i>Bewaar je pincode <b>veilig</b>, dan kan niemand hem stelen.</i> Niet gevaarlijk."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>boos</span>?", o:["kızgın","mutlu","yorgun","üzgün"], c:0,
      e:"<b>boos</b> = kızgın. Voorbeeld: <i>De buurman is boos om het lawaai.</i>",
      tip:"In een zin: <i>De buurman is <b>boos</b> om het lawaai.</i> Hij is niet blij."},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>davetiye</span>?", o:["de uitnodiging","de verjaardag","het gesprek","de gast"], c:0,
      e:"davetiye = <b>de uitnodiging</b>. Je krijgt een uitnodiging voor een feest. 'de verjaardag' = doğum günü.",
      tip:"Denk aan wat je krijgt als je naar een feest mag komen. Welk Nederlands woord hoort daarbij?"},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>hard</span> (sert / yüksek sesli)?", o:["zacht","stil","boos","moe"], c:0,
      e:"<b>hard</b> ↔ <b>zacht</b> (yumuşak / hafif). 'zacht' betekent ook: niet luid.",
      tip:"Een kussen is niet hard, maar juist ...? Denk aan het tegenovergestelde."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vierkant</span>?", o:["kare","yuvarlak","üçgen","uzun"], c:0,
      e:"<b>vierkant</b> = kare. Een vorm met vier gelijke kanten.",
      tip:"Denk aan een vorm met vier gelijke, rechte kanten, zoals een dobbelsteen.", tipImg:"images/vierkant.svg"},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>laag</span> (alçak)?", o:["hoog","breed","rond","licht"], c:0,
      e:"<b>laag</b> = alçak, <b>hoog</b> = yüksek. Dat zijn tegenovergestelden.",
      tip:"Een tafel is laag, maar een flat is juist ...? Denk ver naar boven."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hamer</span>?", o:["çekiç","testere","vida","merdiven"], c:0,
      e:"<b>de hamer</b> = çekiç. Gereedschap om te timmeren.",
      tip:"In een zin: <i>Met een <b>hamer</b> sla ik een spijker in de muur.</i> Gereedschap.", tipImg:"images/hamer.svg"},
  ]},
};

/* ============================================================
   ZINSOPBOUW — leerlijn zinsstructuur (WIE → DOET → WAT → WAAR → WANNEER)
   Deze lessen staan los van de Woordjes-vragenbank en spelen met een eigen,
   simpele engine (zie app.js, blok "Zinsopbouw"). Ze verschijnen automatisch
   onder het kopje "Zinsopbouw" op het dashboard.

   Een Zinsopbouw-les is: { n, num, t, desc, label, intro, items:[…] }.
     n     = uniek id (begin met "Z" zodat het niet botst met de Woordjes-lessen).
     num   = korte badge op de kaart, bijv. "Les 1".
     t     = titel · desc = ondertitel · label = spelvorm-naam op het resultaat.
     intro = korte uitleg (HTML) op het startscherm van de les.
     items = de opdrachten. Elk item heeft een 'kind':

   1) kind:"herken"  — kies het juiste zinsdeel (meerkeuze). Twee vormen:
        a. Zinsdeel zoeken:
           {kind:"herken", sentence:"De man fietst naar school.",
            parts:[["WIE","De man"],["DOET","fietst"],["WAAR","naar school"]],
            ask:"DOET", e:"uitleg (HTML)"}
           De opties zijn automatisch de delen uit 'parts'; goed = het deel bij 'ask'.
        b. Regelvraag (vrije meerkeuze):
           {kind:"herken", q:"vraag (HTML)", o:["…","…"], c:0, e:"uitleg"}
   2) kind:"sleep"   — sleep elk deel naar het juiste vak.
        {kind:"sleep", parts:[["WIE","Ik"],["DOET","koop"],["WAT","brood"],
                              ["WAAR","in de winkel"]], e:"uitleg"}
        De vakken staan in de opgegeven (juiste) volgorde; de delen worden gehusseld.
   3) kind:"bouw"    — vertaal zelf een zin (productief).
        {kind:"bouw", tr:"Turkse zin", model:"Nederlandse voorbeeldzin.",
         answers:["nederlandse voorbeeldzin", "…variant…"],   // goedgekeurde antwoorden
         words:["ik","verhuis (verhuizen)","morgen"],          // Woordenhulp (uit Woordjes)
         e:"uitleg over de woordvolgorde"}

   Geldige rollen: WIE, DOET, WAT, WAAR, WANNEER, EIND.
     (EIND = het tweede werkwoord dat achteraan staat, bijv. 'kopen' in
      "Ik wil een appel kopen." — zie Zinsopbouw les 9.)
   Controleer met: node scripts/validate-lessons.js
   ============================================================ */
const ZINS = [
  {
    n:"Z1", num:"Les 1", t:"Onderwerp en werkwoord", label:"Herkennen",
    desc:"Zoek in een simpele zin het onderwerp (WIE) en het werkwoord (DOET).",
    intro:`<h3>De simpelste vorm</h3>
      <p><b>WIE → DOET → WAT → WAAR → WANNEER</b></p>
      <p>Eerst zeg je <b>wie</b> iets doet, en dan <b>meteen</b> wat die doet.
         Het werkwoord (DOET) staat altijd op <b>plek 2</b>.</p>
      <div class="zin-legend"><span class="zrole r-wie">WIE</span><span class="zrole r-doet">DOET</span><span class="zrole r-wat">WAT</span><span class="zrole r-waar">WAAR</span><span class="zrole r-wanneer">WANNEER</span></div>
      <p>In deze les zoek je steeds de <b>WIE</b> of de <b>DOET</b> in een zin.</p>`,
    items:[
      {kind:"herken", sentence:"Ik eet een appel.",
        parts:[["WIE","Ik"],["DOET","eet"],["WAT","een appel"]], ask:"WIE",
        e:"De <b>WIE</b> is wie iets doet. Hier is dat <b>Ik</b>."},
      {kind:"herken", sentence:"Ik eet een appel.",
        parts:[["WIE","Ik"],["DOET","eet"],["WAT","een appel"]], ask:"DOET",
        e:"De <b>DOET</b> is het werkwoord op plek 2: <b>eet</b>."},
      {kind:"herken", sentence:"De man fietst naar school.",
        parts:[["WIE","De man"],["DOET","fietst"],["WAAR","naar school"]], ask:"WIE",
        e:"Wie fietst er? <b>De man</b>. Dat is de WIE."},
      {kind:"herken", sentence:"De man fietst naar school.",
        parts:[["WIE","De man"],["DOET","fietst"],["WAAR","naar school"]], ask:"DOET",
        e:"Het werkwoord staat op plek 2: <b>fietst</b>."},
      {kind:"herken", sentence:"De buurman is boos.",
        parts:[["WIE","De buurman"],["DOET","is"],["WAT","boos"]], ask:"DOET",
        e:"Ook een klein woord kan het werkwoord zijn: <b>is</b> staat op plek 2."},
      {kind:"herken", sentence:"Wij vieren vanavond de verjaardag.",
        parts:[["WIE","Wij"],["DOET","vieren"],["WANNEER","vanavond"],["WAT","de verjaardag"]], ask:"DOET",
        e:"Het werkwoord blijft op plek 2: <b>vieren</b>. 'Vanavond' komt pas daarna."},
      {kind:"herken",
        q:"Op welke plek staat het werkwoord (DOET) in een gewone zin?",
        o:["Op plek 2","Op plek 1","Helemaal achteraan","Dat wisselt steeds"], c:0,
        e:"Het werkwoord staat <b>altijd op plek 2</b>. Niet eerder, niet later."},
    ],
  },
  {
    n:"Z2", num:"Les 2", t:"Voorwerp, tijd en plaats", label:"Herkennen",
    desc:"Zoek het voorwerp (WAT), de tijd (WANNEER) en de plaats (WAAR) — en leer: tijd vóór plaats.",
    intro:`<h3>Wat, waar en wanneer</h3>
      <p>Na WIE en DOET komt de rest: <b>WAT</b> (of wie), <b>WAAR</b> (de plek) en <b>WANNEER</b> (de tijd).</p>
      <div class="zin-legend"><span class="zrole r-wie">WIE</span><span class="zrole r-doet">DOET</span><span class="zrole r-wat">WAT</span><span class="zrole r-waar">WAAR</span><span class="zrole r-wanneer">WANNEER</span></div>
      <p><b>Belangrijk:</b> WANNEER komt vóór WAAR.<br>
        ✅ Ik ga <i>morgen</i> <i>naar Delft</i>. &nbsp; ❌ Ik ga <i>naar Delft</i> <i>morgen</i>.</p>`,
    items:[
      {kind:"herken", sentence:"Ik eet een appel.",
        parts:[["WIE","Ik"],["DOET","eet"],["WAT","een appel"]], ask:"WAT",
        e:"Wat eet je? <b>een appel</b>. Dat is de WAT."},
      {kind:"herken", sentence:"De man fietst naar school.",
        parts:[["WIE","De man"],["DOET","fietst"],["WAAR","naar school"]], ask:"WAAR",
        e:"Waar fietst hij heen? <b>naar school</b>. Dat is de WAAR (de plek)."},
      {kind:"herken", sentence:"Ik ga morgen naar Delft.",
        parts:[["WIE","Ik"],["DOET","ga"],["WANNEER","morgen"],["WAAR","naar Delft"]], ask:"WANNEER",
        e:"Wanneer ga je? <b>morgen</b>. Dat is de WANNEER (de tijd)."},
      {kind:"herken", sentence:"Ik ga morgen naar Delft.",
        parts:[["WIE","Ik"],["DOET","ga"],["WANNEER","morgen"],["WAAR","naar Delft"]], ask:"WAAR",
        e:"Waar ga je heen? <b>naar Delft</b>. De plek komt ná de tijd."},
      {kind:"herken", sentence:"Wij vieren vanavond de verjaardag.",
        parts:[["WIE","Wij"],["DOET","vieren"],["WANNEER","vanavond"],["WAT","de verjaardag"]], ask:"WAT",
        e:"Wat vieren jullie? <b>de verjaardag</b>. Dat is de WAT."},
      {kind:"herken",
        q:"Wat komt eerst in de zin: de tijd (WANNEER) of de plek (WAAR)?",
        o:["Eerst WANNEER, dan WAAR","Eerst WAAR, dan WANNEER","Dat maakt niet uit","Allebei helemaal achteraan"], c:0,
        e:"<b>WANNEER komt vóór WAAR.</b> Voorbeeld: Ik ga <i>morgen</i> <i>naar Delft</i>."},
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik ga morgen naar Delft.","Ik ga naar Delft morgen."], c:0,
        e:"Goed is: <b>Ik ga morgen naar Delft.</b> De tijd (WANNEER) staat vóór de plek (WAAR)."},
    ],
  },
  {
    n:"Z3", num:"Les 3", t:"De hele zin op volgorde", label:"Slepen & quiz",
    desc:"Sleep elk zinsdeel naar het juiste vak en test jezelf met een paar vragen.",
    intro:`<h3>Zet de hele zin in elkaar</h3>
      <p>Sleep elk deel naar het juiste vak. Let op de volgorde:
         het werkwoord op <b>plek 2</b>, en <b>WANNEER vóór WAAR</b>.</p>
      <p>Op de telefoon: tik een deel en tik daarna het vak.</p>`,
    items:[
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","eet"],["WAT","een appel"]],
        e:"Volgorde: WIE → DOET → WAT. <i>Ik eet een appel.</i>"},
      {kind:"sleep",
        parts:[["WIE","De man"],["DOET","fietst"],["WAAR","naar school"]],
        e:"Volgorde: WIE → DOET → WAAR. <i>De man fietst naar school.</i>"},
      {kind:"herken", sentence:"De trein heeft vandaag vertraging.",
        parts:[["WIE","De trein"],["DOET","heeft"],["WANNEER","vandaag"],["WAT","vertraging"]], ask:"DOET",
        e:"Het werkwoord op plek 2 is <b>heeft</b>."},
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","ga"],["WANNEER","morgen"],["WAAR","naar Delft"]],
        e:"WANNEER vóór WAAR: <i>Ik ga morgen naar Delft.</i>"},
      {kind:"herken",
        q:"Welke zin heeft de goede volgorde?",
        o:["Wij vieren vanavond de verjaardag.","Wij vanavond vieren de verjaardag."], c:0,
        e:"Het werkwoord (vieren) hoort op plek 2: <b>Wij vieren vanavond de verjaardag.</b>"},
      {kind:"sleep",
        parts:[["WIE","Wij"],["DOET","vieren"],["WANNEER","vanavond"],["WAT","de verjaardag"]],
        e:"WIE → DOET → WANNEER → WAT. <i>Wij vieren vanavond de verjaardag.</i>"},
    ],
  },
  {
    n:"Z4", num:"Les 4", t:"Zelf zinnen maken", label:"Vertalen",
    desc:"Vertaal zelf een zin naar het Nederlands. Gebruik de woorden uit de Woordjes-lessen.",
    intro:`<h3>Bouw je eigen zin</h3>
      <p>Nu maak je de zin zelf. Je krijgt een zin in het Turks; typ hem in het Nederlands.
         Gebruik de <b>Woordenhulp</b> — dat zijn woorden die je al leerde bij de Woordjes-lessen.</p>
      <p>Denk aan: het werkwoord op <b>plek 2</b> en <b>WANNEER vóór WAAR</b>.
         Meerdere goede zinnen kunnen kloppen; vergelijk daarna met de voorbeeldzin.</p>`,
    items:[
      {kind:"bouw", tr:"Ben bir elma yiyorum.", model:"Ik eet een appel.",
        answers:["ik eet een appel"], words:["ik","eet (eten)","een appel"],
        e:"WIE (Ik) → DOET (eet, plek 2) → WAT (een appel)."},
      {kind:"bouw", tr:"Ben yarın taşınıyorum.", model:"Ik verhuis morgen.",
        answers:["ik verhuis morgen","morgen verhuis ik"], words:["ik","verhuis (verhuizen)","morgen"],
        e:"Je mag ook met de tijd beginnen: <i>Morgen verhuis ik.</i> Het werkwoord blijft op plek 2."},
      {kind:"bouw", tr:"Adam okula bisikletle gidiyor.", model:"De man fietst naar school.",
        answers:["de man fietst naar school"], words:["de man","fietst (fietsen)","naar school"],
        e:"WIE (De man) → DOET (fietst) → WAAR (naar school)."},
      {kind:"bouw", tr:"Biz bu akşam doğum gününü kutluyoruz.", model:"Wij vieren vanavond de verjaardag.",
        answers:["wij vieren vanavond de verjaardag","we vieren vanavond de verjaardag","vanavond vieren wij de verjaardag","vanavond vieren we de verjaardag"],
        words:["wij","vieren","vanavond","de verjaardag"],
        e:"Werkwoord op plek 2: <i>Wij vieren vanavond de verjaardag.</i>"},
      {kind:"bouw", tr:"Tren bugün gecikmeli.", model:"De trein heeft vandaag vertraging.",
        answers:["de trein heeft vandaag vertraging","vandaag heeft de trein vertraging"],
        words:["de trein","heeft (hebben)","vandaag","de vertraging"],
        e:"WIE (De trein) → DOET (heeft) → WANNEER (vandaag) → WAT (vertraging)."},
      {kind:"bouw", tr:"Ben yarın Delft'e gidiyorum.", model:"Ik ga morgen naar Delft.",
        answers:["ik ga morgen naar delft","morgen ga ik naar delft"],
        words:["ik","ga (gaan)","morgen","naar Delft"],
        e:"WANNEER vóór WAAR: <i>Ik ga morgen naar Delft.</i>"},
    ],
  },
  {
    n:"Z5", num:"Les 5", t:"Vragen stellen", label:"Vragen maken",
    desc:"Maak een ja/nee-vraag: het werkwoord springt naar voren, naar plek 1.",
    intro:`<h3>De vraag: werkwoord vooraan</h3>
      <p>In een gewone zin staat het werkwoord op <b>plek 2</b>.
         In een <b>ja/nee-vraag</b> springt het werkwoord naar <b>plek 1</b>, helemaal vooraan.</p>
      <div class="zin-legend"><span class="zrole r-doet">DOET</span><span class="zrole r-wie">WIE</span><span class="zrole r-wat">WAT</span><span class="zrole r-waar">WAAR</span><span class="zrole r-wanneer">WANNEER</span></div>
      <p>✅ <i>Eet jij een appel?</i> &nbsp;(DOET → WIE → WAT)<br>
         Vergelijk met de gewone zin: <i>Jij eet een appel.</i> (WIE → DOET → WAT)</p>`,
    items:[
      {kind:"herken", sentence:"Eet jij een appel?",
        parts:[["DOET","Eet"],["WIE","jij"],["WAT","een appel"]], ask:"DOET",
        e:"In een vraag staat het werkwoord vooraan: <b>Eet</b> op plek 1."},
      {kind:"herken", sentence:"Eet jij een appel?",
        parts:[["DOET","Eet"],["WIE","jij"],["WAT","een appel"]], ask:"WIE",
        e:"Wie eet er? <b>jij</b>. In een vraag komt het onderwerp ná het werkwoord."},
      {kind:"herken", sentence:"Fietst de man naar school?",
        parts:[["DOET","Fietst"],["WIE","de man"],["WAAR","naar school"]], ask:"DOET",
        e:"Het werkwoord staat vooraan: <b>Fietst</b>."},
      {kind:"herken",
        q:"Waar staat het werkwoord in een ja/nee-vraag?",
        o:["Op plek 1 (vooraan)","Op plek 2","Helemaal achteraan","Dat wisselt steeds"], c:0,
        e:"In een <b>ja/nee-vraag</b> staat het werkwoord op <b>plek 1</b>, vooraan."},
      {kind:"herken",
        q:"Welke zin is een goede vraag?",
        o:["Ga jij morgen naar Delft?","Jij ga morgen naar Delft?"], c:0,
        e:"Goed is: <b>Ga jij morgen naar Delft?</b> Het werkwoord (Ga) staat vooraan."},
      {kind:"sleep",
        parts:[["DOET","Fietst"],["WIE","de man"],["WAAR","naar school"]],
        e:"Vraag-volgorde: DOET → WIE → WAAR. <i>Fietst de man naar school?</i>"},
      {kind:"sleep",
        parts:[["DOET","Ga"],["WIE","jij"],["WANNEER","morgen"],["WAAR","naar Delft"]],
        e:"Werkwoord vooraan én WANNEER vóór WAAR. <i>Ga jij morgen naar Delft?</i>"},
      {kind:"bouw", tr:"Bir elma yiyor musun?", model:"Eet jij een appel?",
        answers:["eet jij een appel","eet je een appel"], words:["eet (eten)","jij","een appel"],
        e:"Werkwoord vooraan: <i>Eet jij een appel?</i>"},
      {kind:"bouw", tr:"Yarın Delft'e gidiyor musun?", model:"Ga jij morgen naar Delft?",
        answers:["ga jij morgen naar delft","ga je morgen naar delft"], words:["ga (gaan)","jij","morgen","naar Delft"],
        e:"DOET (Ga) vooraan, WANNEER (morgen) vóór WAAR (naar Delft)."},
      {kind:"bouw", tr:"Bu akşam geliyor musun?", model:"Kom jij vanavond?",
        answers:["kom jij vanavond","kom je vanavond"], words:["kom (komen)","jij","vanavond"],
        e:"Korte vraag, werkwoord vooraan: <i>Kom jij vanavond?</i>"},
    ],
  },
  {
    n:"Z6", num:"Les 6", t:"Nee zeggen", label:"Ontkennen",
    desc:"Ontken een zin: kies tussen geen (bij een zelfstandig naamwoord) en niet (de rest).",
    intro:`<h3>geen of niet?</h3>
      <p>Wil je iets ontkennen? Dan gebruik je <b>geen</b> of <b>niet</b>.</p>
      <p>• <b>geen</b> staat vóór een zelfstandig naamwoord (in plaats van <i>een</i>):<br>
         <i>Ik heb een appel.</i> → <i>Ik heb <b>geen</b> appel.</i></p>
      <p>• <b>niet</b> gebruik je voor de rest. <b>niet</b> staat meestal achteraan,
         maar vóór een plaats: <i>Ik fiets <b>niet</b>.</i> &nbsp; <i>Ik ga <b>niet</b> naar school.</i></p>`,
    items:[
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik heb geen appel.","Ik heb niet appel."], c:0,
        e:"Bij een zelfstandig naamwoord (appel) gebruik je <b>geen</b>: <i>Ik heb geen appel.</i>"},
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik fiets niet.","Ik fiets geen."], c:0,
        e:"Hier is geen zelfstandig naamwoord, dus <b>niet</b>: <i>Ik fiets niet.</i>"},
      {kind:"herken",
        q:"Vul in: Ik drink ___ koffie.",
        o:["geen","niet"], c:0,
        e:"Vóór een zelfstandig naamwoord (koffie): <b>geen</b>. <i>Ik drink geen koffie.</i>"},
      {kind:"herken",
        q:"Vul in: De soep is ___ warm.",
        o:["niet","geen"], c:0,
        e:"Vóór een bijvoeglijk naamwoord (warm): <b>niet</b>. <i>De soep is niet warm.</i>"},
      {kind:"herken", sentence:"Ik eet geen brood.",
        parts:[["WIE","Ik"],["DOET","eet"],["WAT","geen brood"]], ask:"WAT",
        e:"Wat eet je niet? <b>geen brood</b>. 'geen' hoort bij het zelfstandig naamwoord."},
      {kind:"herken",
        q:"Waar staat 'niet' meestal in een korte zin?",
        o:["Achteraan","Vooraan","Op plek 2","Vlak na het onderwerp"], c:0,
        e:"<b>niet</b> staat meestal <b>achteraan</b>: <i>Ik fiets niet.</i> (maar vóór een plaats: <i>Ik ga niet naar school.</i>)"},
      {kind:"bouw", tr:"Ekmeğim yok.", model:"Ik heb geen brood.",
        answers:["ik heb geen brood"], words:["ik","heb (hebben)","geen brood"],
        e:"Bij een zelfstandig naamwoord: <b>geen</b>. <i>Ik heb geen brood.</i>"},
      {kind:"bouw", tr:"Okula gitmiyorum.", model:"Ik ga niet naar school.",
        answers:["ik ga niet naar school"], words:["ik","ga (gaan)","niet","naar school"],
        e:"<b>niet</b> vóór de plaats: <i>Ik ga niet naar school.</i>"},
      {kind:"bouw", tr:"Kahve içmiyorum.", model:"Ik drink geen koffie.",
        answers:["ik drink geen koffie"], words:["ik","drink (drinken)","geen koffie"],
        e:"Bij het zelfstandig naamwoord koffie: <b>geen</b>. <i>Ik drink geen koffie.</i>"},
    ],
  },
  {
    n:"Z7", num:"Les 7", t:"Grote mix: alles door elkaar", label:"Mix",
    desc:"Alle zinsopbouw uit les 1 t/m 6 in één les: herkennen, slepen, bouwen, vragen en nee zeggen — met nieuwe zinnen.",
    intro:`<h3>Alles door elkaar</h3>
      <p>In deze les komt <b>alles</b> uit les 1 t/m 6 terug: het onderwerp (WIE) en het werkwoord (DOET),
         de WAT, WAAR en WANNEER, zinnen <b>slepen</b>, zelf zinnen <b>bouwen</b>, een <b>vraag</b> maken en <b>nee</b> zeggen.</p>
      <div class="zin-legend"><span class="zrole r-wie">WIE</span><span class="zrole r-doet">DOET</span><span class="zrole r-wat">WAT</span><span class="zrole r-waar">WAAR</span><span class="zrole r-wanneer">WANNEER</span></div>
      <p>Onthoud de twee vaste regels: het werkwoord op <b>plek 2</b>, en <b>WANNEER vóór WAAR</b>.
         De zinnen zijn nieuw, maar het niveau is hetzelfde.</p>`,
    items:[
      {kind:"herken", sentence:"De buurvrouw koopt een spiegel.",
        parts:[["WIE","De buurvrouw"],["DOET","koopt"],["WAT","een spiegel"]], ask:"WIE",
        e:"Wie koopt er iets? <b>De buurvrouw</b>. Dat is de WIE."},
      {kind:"herken", sentence:"De kinderen spelen in de tuin.",
        parts:[["WIE","De kinderen"],["DOET","spelen"],["WAAR","in de tuin"]], ask:"DOET",
        e:"Het werkwoord staat op plek 2: <b>spelen</b>."},
      {kind:"herken", sentence:"Ik verkoop mijn oude bank.",
        parts:[["WIE","Ik"],["DOET","verkoop"],["WAT","mijn oude bank"]], ask:"WAT",
        e:"Wat verkoop je? <b>mijn oude bank</b>. Dat is de WAT."},
      {kind:"herken", sentence:"De gast komt overmorgen.",
        parts:[["WIE","De gast"],["DOET","komt"],["WANNEER","overmorgen"]], ask:"WANNEER",
        e:"Wanneer komt de gast? <b>overmorgen</b>. Dat is de WANNEER (de tijd)."},
      {kind:"herken", sentence:"Wij gaan naar de markt.",
        parts:[["WIE","Wij"],["DOET","gaan"],["WAAR","naar de markt"]], ask:"WAAR",
        e:"Waar gaan jullie heen? <b>naar de markt</b>. Dat is de WAAR (de plek)."},
      {kind:"herken",
        q:"Welke zin heeft de goede volgorde?",
        o:["Ik drink elke dag koffie.","Ik elke dag drink koffie."], c:0,
        e:"Het werkwoord (drink) hoort op plek 2: <b>Ik drink elke dag koffie.</b>"},
      {kind:"sleep",
        parts:[["WIE","De gast"],["DOET","komt"],["WANNEER","overmorgen"],["WAAR","naar ons huis"]],
        e:"WANNEER vóór WAAR: <i>De gast komt overmorgen naar ons huis.</i>"},
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","koop"],["WAT","een kleed"],["WAAR","op de markt"]],
        e:"WIE → DOET → WAT → WAAR: <i>Ik koop een kleed op de markt.</i>"},
      {kind:"herken",
        q:"Welke zin is een goede vraag?",
        o:["Koop jij een spiegel?","Jij koop een spiegel?"], c:0,
        e:"In een ja/nee-vraag staat het werkwoord vooraan: <b>Koop jij een spiegel?</b>"},
      {kind:"herken",
        q:"Vul in: Ik heb ___ tijd. (geen of niet?)",
        o:["geen","niet"], c:0,
        e:"Vóór een zelfstandig naamwoord (tijd) gebruik je <b>geen</b>: <i>Ik heb geen tijd.</i>"},
      {kind:"bouw", tr:"Misafir bu akşam geliyor.", model:"De gast komt vanavond.",
        answers:["de gast komt vanavond","vanavond komt de gast"],
        words:["de gast","komt (komen)","vanavond"],
        e:"WIE (De gast) → DOET (komt) → WANNEER (vanavond)."},
      {kind:"bouw", tr:"Eski koltuğumu satıyorum.", model:"Ik verkoop mijn oude bank.",
        answers:["ik verkoop mijn oude bank"],
        words:["ik","verkoop (verkopen)","mijn oude bank"],
        e:"WIE (Ik) → DOET (verkoop, plek 2) → WAT (mijn oude bank)."},
      {kind:"bouw", tr:"Yarın markete gidiyorum.", model:"Ik ga morgen naar de markt.",
        answers:["ik ga morgen naar de markt","morgen ga ik naar de markt"],
        words:["ik","ga (gaan)","morgen","naar de markt"],
        e:"WANNEER vóór WAAR: <i>Ik ga morgen naar de markt.</i>"},
    ],
  },
  {
    n:"Z8", num:"Les 8", t:"Een stap verder: omdraaien & langere zinnen", label:"Uitdaging",
    desc:"Iets moeilijker: begin met de tijd of plaats (het werkwoord blijft op plek 2), maak langere zinnen en open vragen.",
    intro:`<h3>Een stap verder</h3>
      <p>Je kent de gewone volgorde al. Nu draaien we de zin soms <b>om</b>: je begint met de <b>tijd</b> of de <b>plaats</b>.
         Dan blijft het werkwoord op <b>plek 2</b>, en het onderwerp (WIE) springt naar <b>ná</b> het werkwoord.</p>
      <div class="zin-legend"><span class="zrole r-wanneer">WANNEER</span><span class="zrole r-doet">DOET</span><span class="zrole r-wie">WIE</span><span class="zrole r-waar">WAAR</span></div>
      <p>✅ <i>Morgen ga ik naar het station.</i> &nbsp; ❌ <i>Morgen ik ga naar het station.</i></p>
      <p>Ook maak je nu <b>langere zinnen</b> met alle delen, en <b>open vragen</b> met een vraagwoord (waar, wanneer).</p>`,
    items:[
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Morgen ga ik naar het station.","Morgen ik ga naar het station."], c:0,
        e:"Begin je met de tijd, dan blijft het werkwoord op plek 2: <b>Morgen ga ik…</b> Het onderwerp (ik) komt ná het werkwoord."},
      {kind:"herken", sentence:"Vanavond komt de gast.",
        parts:[["WANNEER","Vanavond"],["DOET","komt"],["WIE","de gast"]], ask:"DOET",
        e:"Ook na de tijd staat het werkwoord op plek 2: <b>komt</b>."},
      {kind:"herken", sentence:"Vanavond komt de gast.",
        parts:[["WANNEER","Vanavond"],["DOET","komt"],["WIE","de gast"]], ask:"WIE",
        e:"Wie komt er? <b>de gast</b>. In een omgedraaide zin komt het onderwerp ná het werkwoord."},
      {kind:"herken",
        q:"Je begint een zin met 'Morgen'. Waar staat het werkwoord dan?",
        o:["Nog steeds op plek 2","Op plek 1 (vooraan)","Helemaal achteraan"], c:0,
        e:"Het werkwoord blijft <b>altijd op plek 2</b>. Na 'Morgen' komt dus meteen het werkwoord, en dán het onderwerp."},
      {kind:"sleep",
        parts:[["WANNEER","Morgen"],["DOET","ga"],["WIE","ik"],["WAAR","naar het station"]],
        e:"Begin met de tijd → werkwoord op plek 2, dan de WIE: <i>Morgen ga ik naar het station.</i>"},
      {kind:"herken", sentence:"Op de markt koop ik een kleed.",
        parts:[["WAAR","Op de markt"],["DOET","koop"],["WIE","ik"],["WAT","een kleed"]], ask:"DOET",
        e:"Je begint hier met de plaats. Het werkwoord blijft op plek 2: <b>koop</b>."},
      {kind:"herken", sentence:"De buurman koopt vandaag een nieuwe bank.",
        parts:[["WIE","De buurman"],["DOET","koopt"],["WANNEER","vandaag"],["WAT","een nieuwe bank"]], ask:"WANNEER",
        e:"Wanneer koopt hij de bank? <b>vandaag</b>. Dat is de WANNEER."},
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","koop"],["WANNEER","morgen"],["WAT","een kleed"],["WAAR","op de markt"]],
        e:"Een langere zin met alle delen. WANNEER vóór WAAR: <i>Ik koop morgen een kleed op de markt.</i>"},
      {kind:"herken",
        q:"Welke vraag is goed?",
        o:["Waar woon jij?","Waar jij woont?"], c:0,
        e:"Na een vraagwoord (waar) staat het werkwoord op plek 2: <b>Waar woon jij?</b>"},
      {kind:"bouw", tr:"Yarın istasyona gidiyorum.", model:"Morgen ga ik naar het station.",
        answers:["morgen ga ik naar het station","ik ga morgen naar het station"],
        words:["morgen","ga (gaan)","ik","naar het station"],
        e:"Begin je met 'Morgen', dan komt het werkwoord (ga) meteen daarna, en dán 'ik'."},
      {kind:"bouw", tr:"Komşu bugün yeni bir koltuk alıyor.", model:"De buurman koopt vandaag een nieuwe bank.",
        answers:["de buurman koopt vandaag een nieuwe bank","vandaag koopt de buurman een nieuwe bank"],
        words:["de buurman","koopt (kopen)","vandaag","een nieuwe bank"],
        e:"Een langere zin: WIE → DOET → WANNEER → WAT. Je mag ook met 'vandaag' beginnen."},
      {kind:"bouw", tr:"Nerede oturuyorsun?", model:"Waar woon jij?",
        answers:["waar woon jij","waar woon je"],
        words:["waar","woon (wonen)","jij"],
        e:"Een open vraag met een vraagwoord: <b>Waar</b> + werkwoord op plek 2 + WIE (jij)."},
    ],
  },
  {
    n:"Z9", num:"Les 9", t:"Twee werkwoorden: de rest gaat naar het eind", label:"Uitdaging+",
    desc:"Zinnen met willen, kunnen, moeten of gaan: het eerste werkwoord op plek 2, het tweede werkwoord (EIND) helemaal achteraan.",
    intro:`<h3>Twee werkwoorden in één zin</h3>
      <p>Soms staan er <b>twee werkwoorden</b> in een zin, bijvoorbeeld met <i>willen, kunnen, moeten</i> of <i>gaan</i>.
         Dan blijft het eerste werkwoord (DOET) op <b>plek 2</b>, en het <b>tweede werkwoord</b> springt helemaal naar het <b>eind</b>.</p>
      <div class="zin-legend"><span class="zrole r-wie">WIE</span><span class="zrole r-doet">DOET</span><span class="zrole r-wat">WAT</span><span class="zrole r-eind">EIND</span></div>
      <p>✅ <i>Ik wil een appel <b>kopen</b>.</i> &nbsp; ❌ <i>Ik wil kopen een appel.</i></p>
      <p>Het tweede werkwoord (kopen) staat dus <b>achteraan</b>. Alles wat erbij hoort — WAT, WAAR, WANNEER — komt ertussen.</p>`,
    items:[
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik wil een appel kopen.","Ik wil kopen een appel."], c:0,
        e:"Het tweede werkwoord (kopen) staat achteraan: <b>Ik wil een appel kopen.</b>"},
      {kind:"herken", sentence:"Ik wil een appel kopen.",
        parts:[["WIE","Ik"],["DOET","wil"],["WAT","een appel"],["EIND","kopen"]], ask:"EIND",
        e:"Het tweede werkwoord staat helemaal achteraan: <b>kopen</b>. Dat is de EIND."},
      {kind:"herken", sentence:"Ik wil een appel kopen.",
        parts:[["WIE","Ik"],["DOET","wil"],["WAT","een appel"],["EIND","kopen"]], ask:"DOET",
        e:"Het eerste werkwoord blijft op plek 2: <b>wil</b>."},
      {kind:"herken",
        q:"Waar staat het tweede werkwoord in een zin met twee werkwoorden?",
        o:["Achteraan (op het eind)","Op plek 2","Op plek 1 (vooraan)","Vlak na het onderwerp"], c:0,
        e:"Het tweede werkwoord springt naar het <b>eind</b> van de zin. Het eerste werkwoord blijft op plek 2."},
      {kind:"herken", sentence:"De kinderen moeten naar school gaan.",
        parts:[["WIE","De kinderen"],["DOET","moeten"],["WAAR","naar school"],["EIND","gaan"]], ask:"EIND",
        e:"Het tweede werkwoord staat achteraan: <b>gaan</b>."},
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","wil"],["WAT","een spiegel"],["EIND","kopen"]],
        e:"Eerste werkwoord op plek 2, tweede werkwoord achteraan: <i>Ik wil een spiegel kopen.</i>"},
      {kind:"sleep",
        parts:[["WIE","Wij"],["DOET","gaan"],["WANNEER","vanavond"],["WAT","de verjaardag"],["EIND","vieren"]],
        e:"Alles komt ertussen, 'vieren' achteraan: <i>Wij gaan vanavond de verjaardag vieren.</i>"},
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik moet morgen de huur betalen.","Ik moet betalen morgen de huur."], c:0,
        e:"Het tweede werkwoord (betalen) staat achteraan: <b>Ik moet morgen de huur betalen.</b>"},
      {kind:"bouw", tr:"Bir elma almak istiyorum.", model:"Ik wil een appel kopen.",
        answers:["ik wil een appel kopen"],
        words:["ik","wil (willen)","een appel","kopen"],
        e:"DOET (wil) op plek 2 → WAT (een appel) → EIND (kopen) achteraan."},
      {kind:"bouw", tr:"Yarın Delft'e gitmek istiyorum.", model:"Ik wil morgen naar Delft gaan.",
        answers:["ik wil morgen naar delft gaan","morgen wil ik naar delft gaan"],
        words:["ik","wil (willen)","morgen","naar Delft","gaan"],
        e:"'wil' op plek 2, WANNEER vóór WAAR, en 'gaan' helemaal achteraan."},
      {kind:"bouw", tr:"Kirayı ödemem gerekiyor.", model:"Ik moet de huur betalen.",
        answers:["ik moet de huur betalen"],
        words:["ik","moet (moeten)","de huur","betalen"],
        e:"DOET (moet) op plek 2 → WAT (de huur) → EIND (betalen) achteraan."},
      {kind:"bouw", tr:"Bu akşam doğum gününü kutlamak istiyoruz.", model:"Wij willen vanavond de verjaardag vieren.",
        answers:["wij willen vanavond de verjaardag vieren","we willen vanavond de verjaardag vieren"],
        words:["wij","willen","vanavond","de verjaardag","vieren"],
        e:"'willen' op plek 2 → WANNEER (vanavond) → WAT (de verjaardag) → EIND (vieren) achteraan."},
    ],
  },
];

/* ============================================================
   ZINSOPBOUW 2 — tweede leerlijn zinsstructuur (zelfde theorie, andere zinnen)
   Dit is een 1-op-1 kopie van de leerlijn Zinsopbouw (ZINS hierboven): exact
   dezelfde vraagtheorie en dezelfde opbouw les voor les, maar met totaal andere
   opdrachten en woorden. Waar leerlijn 1 vraagt "wie loopt?", vraagt leerlijn 2
   bijvoorbeeld "wie rent?". Zo kan een leerling die leerlijn 1 kent, met nieuwe
   zinnen oefenen zonder de antwoorden al te weten.

   Zelfde structuur als ZINS: { n, num, t, desc, label, intro, items:[…] }.
   De id's beginnen met "Y" zodat ze niet botsen met leerlijn 1 ("Z") of de
   Woordjes-lessen. Controleer met: node scripts/validate-lessons.js
   ============================================================ */
const ZINS2 = [
  {
    n:"Y1", num:"Les 1", t:"Onderwerp en werkwoord", label:"Herkennen",
    desc:"Zoek in een simpele zin het onderwerp (WIE) en het werkwoord (DOET).",
    intro:`<h3>De simpelste vorm</h3>
      <p><b>WIE → DOET → WAT → WAAR → WANNEER</b></p>
      <p>Eerst zeg je <b>wie</b> iets doet, en dan <b>meteen</b> wat die doet.
         Het werkwoord (DOET) staat altijd op <b>plek 2</b>.</p>
      <div class="zin-legend"><span class="zrole r-wie">WIE</span><span class="zrole r-doet">DOET</span><span class="zrole r-wat">WAT</span><span class="zrole r-waar">WAAR</span><span class="zrole r-wanneer">WANNEER</span></div>
      <p>In deze les zoek je steeds de <b>WIE</b> of de <b>DOET</b> in een zin.</p>`,
    items:[
      {kind:"herken", sentence:"De vrouw drinkt koffie.",
        parts:[["WIE","De vrouw"],["DOET","drinkt"],["WAT","koffie"]], ask:"WIE",
        e:"De <b>WIE</b> is wie iets doet. Hier is dat <b>De vrouw</b>."},
      {kind:"herken", sentence:"De vrouw drinkt koffie.",
        parts:[["WIE","De vrouw"],["DOET","drinkt"],["WAT","koffie"]], ask:"DOET",
        e:"De <b>DOET</b> is het werkwoord op plek 2: <b>drinkt</b>."},
      {kind:"herken", sentence:"Het kind rent naar de tuin.",
        parts:[["WIE","Het kind"],["DOET","rent"],["WAAR","naar de tuin"]], ask:"WIE",
        e:"Wie rent er? <b>Het kind</b>. Dat is de WIE."},
      {kind:"herken", sentence:"Het kind rent naar de tuin.",
        parts:[["WIE","Het kind"],["DOET","rent"],["WAAR","naar de tuin"]], ask:"DOET",
        e:"Het werkwoord staat op plek 2: <b>rent</b>."},
      {kind:"herken", sentence:"De hond is ziek.",
        parts:[["WIE","De hond"],["DOET","is"],["WAT","ziek"]], ask:"DOET",
        e:"Ook een klein woord kan het werkwoord zijn: <b>is</b> staat op plek 2."},
      {kind:"herken", sentence:"Wij eten vanavond pizza.",
        parts:[["WIE","Wij"],["DOET","eten"],["WANNEER","vanavond"],["WAT","pizza"]], ask:"DOET",
        e:"Het werkwoord blijft op plek 2: <b>eten</b>. 'Vanavond' komt pas daarna."},
      {kind:"herken",
        q:"Op welke plek staat het werkwoord (DOET) in een gewone zin?",
        o:["Op plek 2","Op plek 1","Helemaal achteraan","Dat wisselt steeds"], c:0,
        e:"Het werkwoord staat <b>altijd op plek 2</b>. Niet eerder, niet later."},
    ],
  },
  {
    n:"Y2", num:"Les 2", t:"Voorwerp, tijd en plaats", label:"Herkennen",
    desc:"Zoek het voorwerp (WAT), de tijd (WANNEER) en de plaats (WAAR) — en leer: tijd vóór plaats.",
    intro:`<h3>Wat, waar en wanneer</h3>
      <p>Na WIE en DOET komt de rest: <b>WAT</b> (of wie), <b>WAAR</b> (de plek) en <b>WANNEER</b> (de tijd).</p>
      <div class="zin-legend"><span class="zrole r-wie">WIE</span><span class="zrole r-doet">DOET</span><span class="zrole r-wat">WAT</span><span class="zrole r-waar">WAAR</span><span class="zrole r-wanneer">WANNEER</span></div>
      <p><b>Belangrijk:</b> WANNEER komt vóór WAAR.<br>
        ✅ Ik ga <i>zaterdag</i> <i>naar de stad</i>. &nbsp; ❌ Ik ga <i>naar de stad</i> <i>zaterdag</i>.</p>`,
    items:[
      {kind:"herken", sentence:"De vrouw drinkt koffie.",
        parts:[["WIE","De vrouw"],["DOET","drinkt"],["WAT","koffie"]], ask:"WAT",
        e:"Wat drinkt zij? <b>koffie</b>. Dat is de WAT."},
      {kind:"herken", sentence:"Het kind rent naar de tuin.",
        parts:[["WIE","Het kind"],["DOET","rent"],["WAAR","naar de tuin"]], ask:"WAAR",
        e:"Waar rent het naartoe? <b>naar de tuin</b>. Dat is de WAAR (de plek)."},
      {kind:"herken", sentence:"Ik ga zaterdag naar de stad.",
        parts:[["WIE","Ik"],["DOET","ga"],["WANNEER","zaterdag"],["WAAR","naar de stad"]], ask:"WANNEER",
        e:"Wanneer ga je? <b>zaterdag</b>. Dat is de WANNEER (de tijd)."},
      {kind:"herken", sentence:"Ik ga zaterdag naar de stad.",
        parts:[["WIE","Ik"],["DOET","ga"],["WANNEER","zaterdag"],["WAAR","naar de stad"]], ask:"WAAR",
        e:"Waar ga je heen? <b>naar de stad</b>. De plek komt ná de tijd."},
      {kind:"herken", sentence:"Wij eten vanavond pizza.",
        parts:[["WIE","Wij"],["DOET","eten"],["WANNEER","vanavond"],["WAT","pizza"]], ask:"WAT",
        e:"Wat eten jullie? <b>pizza</b>. Dat is de WAT."},
      {kind:"herken",
        q:"Wat komt eerst in de zin: de tijd (WANNEER) of de plek (WAAR)?",
        o:["Eerst WANNEER, dan WAAR","Eerst WAAR, dan WANNEER","Dat maakt niet uit","Allebei helemaal achteraan"], c:0,
        e:"<b>WANNEER komt vóór WAAR.</b> Voorbeeld: Ik ga <i>zaterdag</i> <i>naar de stad</i>."},
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik ga zaterdag naar de stad.","Ik ga naar de stad zaterdag."], c:0,
        e:"Goed is: <b>Ik ga zaterdag naar de stad.</b> De tijd (WANNEER) staat vóór de plek (WAAR)."},
    ],
  },
  {
    n:"Y3", num:"Les 3", t:"De hele zin op volgorde", label:"Slepen & quiz",
    desc:"Sleep elk zinsdeel naar het juiste vak en test jezelf met een paar vragen.",
    intro:`<h3>Zet de hele zin in elkaar</h3>
      <p>Sleep elk deel naar het juiste vak. Let op de volgorde:
         het werkwoord op <b>plek 2</b>, en <b>WANNEER vóór WAAR</b>.</p>
      <p>Op de telefoon: tik een deel en tik daarna het vak.</p>`,
    items:[
      {kind:"sleep",
        parts:[["WIE","De vrouw"],["DOET","drinkt"],["WAT","koffie"]],
        e:"Volgorde: WIE → DOET → WAT. <i>De vrouw drinkt koffie.</i>"},
      {kind:"sleep",
        parts:[["WIE","Het kind"],["DOET","rent"],["WAAR","naar de tuin"]],
        e:"Volgorde: WIE → DOET → WAAR. <i>Het kind rent naar de tuin.</i>"},
      {kind:"herken", sentence:"De bus heeft vandaag vertraging.",
        parts:[["WIE","De bus"],["DOET","heeft"],["WANNEER","vandaag"],["WAT","vertraging"]], ask:"DOET",
        e:"Het werkwoord op plek 2 is <b>heeft</b>."},
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","ga"],["WANNEER","zaterdag"],["WAAR","naar de stad"]],
        e:"WANNEER vóór WAAR: <i>Ik ga zaterdag naar de stad.</i>"},
      {kind:"herken",
        q:"Welke zin heeft de goede volgorde?",
        o:["Wij eten vanavond pizza.","Wij vanavond eten pizza."], c:0,
        e:"Het werkwoord (eten) hoort op plek 2: <b>Wij eten vanavond pizza.</b>"},
      {kind:"sleep",
        parts:[["WIE","Wij"],["DOET","eten"],["WANNEER","vanavond"],["WAT","pizza"]],
        e:"WIE → DOET → WANNEER → WAT. <i>Wij eten vanavond pizza.</i>"},
    ],
  },
  {
    n:"Y4", num:"Les 4", t:"Zelf zinnen maken", label:"Vertalen",
    desc:"Vertaal zelf een zin naar het Nederlands. Gebruik de woorden uit de Woordjes-lessen.",
    intro:`<h3>Bouw je eigen zin</h3>
      <p>Nu maak je de zin zelf. Je krijgt een zin in het Turks; typ hem in het Nederlands.
         Gebruik de <b>Woordenhulp</b> — dat zijn woorden die je al leerde bij de Woordjes-lessen.</p>
      <p>Denk aan: het werkwoord op <b>plek 2</b> en <b>WANNEER vóór WAAR</b>.
         Meerdere goede zinnen kunnen kloppen; vergelijk daarna met de voorbeeldzin.</p>`,
    items:[
      {kind:"bouw", tr:"Ben kahve içiyorum.", model:"Ik drink koffie.",
        answers:["ik drink koffie"], words:["ik","drink (drinken)","koffie"],
        e:"WIE (Ik) → DOET (drink, plek 2) → WAT (koffie)."},
      {kind:"bouw", tr:"Ben yarın çalışıyorum.", model:"Ik werk morgen.",
        answers:["ik werk morgen","morgen werk ik"], words:["ik","werk (werken)","morgen"],
        e:"Je mag ook met de tijd beginnen: <i>Morgen werk ik.</i> Het werkwoord blijft op plek 2."},
      {kind:"bouw", tr:"Çocuk bahçeye koşuyor.", model:"Het kind rent naar de tuin.",
        answers:["het kind rent naar de tuin"], words:["het kind","rent (rennen)","naar de tuin"],
        e:"WIE (Het kind) → DOET (rent) → WAAR (naar de tuin)."},
      {kind:"bouw", tr:"Biz bu akşam pizza yiyoruz.", model:"Wij eten vanavond pizza.",
        answers:["wij eten vanavond pizza","we eten vanavond pizza","vanavond eten wij pizza","vanavond eten we pizza"],
        words:["wij","eten","vanavond","pizza"],
        e:"Werkwoord op plek 2: <i>Wij eten vanavond pizza.</i>"},
      {kind:"bouw", tr:"Otobüs bugün gecikmeli.", model:"De bus heeft vandaag vertraging.",
        answers:["de bus heeft vandaag vertraging","vandaag heeft de bus vertraging"],
        words:["de bus","heeft (hebben)","vandaag","de vertraging"],
        e:"WIE (De bus) → DOET (heeft) → WANNEER (vandaag) → WAT (vertraging)."},
      {kind:"bouw", tr:"Ben cumartesi şehre gidiyorum.", model:"Ik ga zaterdag naar de stad.",
        answers:["ik ga zaterdag naar de stad","zaterdag ga ik naar de stad"],
        words:["ik","ga (gaan)","zaterdag","naar de stad"],
        e:"WANNEER vóór WAAR: <i>Ik ga zaterdag naar de stad.</i>"},
    ],
  },
  {
    n:"Y5", num:"Les 5", t:"Vragen stellen", label:"Vragen maken",
    desc:"Maak een ja/nee-vraag: het werkwoord springt naar voren, naar plek 1.",
    intro:`<h3>De vraag: werkwoord vooraan</h3>
      <p>In een gewone zin staat het werkwoord op <b>plek 2</b>.
         In een <b>ja/nee-vraag</b> springt het werkwoord naar <b>plek 1</b>, helemaal vooraan.</p>
      <div class="zin-legend"><span class="zrole r-doet">DOET</span><span class="zrole r-wie">WIE</span><span class="zrole r-wat">WAT</span><span class="zrole r-waar">WAAR</span><span class="zrole r-wanneer">WANNEER</span></div>
      <p>✅ <i>Drink jij koffie?</i> &nbsp;(DOET → WIE → WAT)<br>
         Vergelijk met de gewone zin: <i>Jij drinkt koffie.</i> (WIE → DOET → WAT)</p>`,
    items:[
      {kind:"herken", sentence:"Drink jij koffie?",
        parts:[["DOET","Drink"],["WIE","jij"],["WAT","koffie"]], ask:"DOET",
        e:"In een vraag staat het werkwoord vooraan: <b>Drink</b> op plek 1."},
      {kind:"herken", sentence:"Drink jij koffie?",
        parts:[["DOET","Drink"],["WIE","jij"],["WAT","koffie"]], ask:"WIE",
        e:"Wie drinkt er? <b>jij</b>. In een vraag komt het onderwerp ná het werkwoord."},
      {kind:"herken", sentence:"Rent het kind naar de tuin?",
        parts:[["DOET","Rent"],["WIE","het kind"],["WAAR","naar de tuin"]], ask:"DOET",
        e:"Het werkwoord staat vooraan: <b>Rent</b>."},
      {kind:"herken",
        q:"Waar staat het werkwoord in een ja/nee-vraag?",
        o:["Op plek 1 (vooraan)","Op plek 2","Helemaal achteraan","Dat wisselt steeds"], c:0,
        e:"In een <b>ja/nee-vraag</b> staat het werkwoord op <b>plek 1</b>, vooraan."},
      {kind:"herken",
        q:"Welke zin is een goede vraag?",
        o:["Ga jij zaterdag naar de stad?","Jij ga zaterdag naar de stad?"], c:0,
        e:"Goed is: <b>Ga jij zaterdag naar de stad?</b> Het werkwoord (Ga) staat vooraan."},
      {kind:"sleep",
        parts:[["DOET","Rent"],["WIE","het kind"],["WAAR","naar de tuin"]],
        e:"Vraag-volgorde: DOET → WIE → WAAR. <i>Rent het kind naar de tuin?</i>"},
      {kind:"sleep",
        parts:[["DOET","Ga"],["WIE","jij"],["WANNEER","zaterdag"],["WAAR","naar de stad"]],
        e:"Werkwoord vooraan én WANNEER vóór WAAR. <i>Ga jij zaterdag naar de stad?</i>"},
      {kind:"bouw", tr:"Kahve içiyor musun?", model:"Drink jij koffie?",
        answers:["drink jij koffie","drink je koffie"], words:["drink (drinken)","jij","koffie"],
        e:"Werkwoord vooraan: <i>Drink jij koffie?</i>"},
      {kind:"bouw", tr:"Cumartesi şehre gidiyor musun?", model:"Ga jij zaterdag naar de stad?",
        answers:["ga jij zaterdag naar de stad","ga je zaterdag naar de stad"], words:["ga (gaan)","jij","zaterdag","naar de stad"],
        e:"DOET (Ga) vooraan, WANNEER (zaterdag) vóór WAAR (naar de stad)."},
      {kind:"bouw", tr:"Bu akşam çalışıyor musun?", model:"Werk jij vanavond?",
        answers:["werk jij vanavond","werk je vanavond"], words:["werk (werken)","jij","vanavond"],
        e:"Korte vraag, werkwoord vooraan: <i>Werk jij vanavond?</i>"},
    ],
  },
  {
    n:"Y6", num:"Les 6", t:"Nee zeggen", label:"Ontkennen",
    desc:"Ontken een zin: kies tussen geen (bij een zelfstandig naamwoord) en niet (de rest).",
    intro:`<h3>geen of niet?</h3>
      <p>Wil je iets ontkennen? Dan gebruik je <b>geen</b> of <b>niet</b>.</p>
      <p>• <b>geen</b> staat vóór een zelfstandig naamwoord (in plaats van <i>een</i>):<br>
         <i>Ik heb een auto.</i> → <i>Ik heb <b>geen</b> auto.</i></p>
      <p>• <b>niet</b> gebruik je voor de rest. <b>niet</b> staat meestal achteraan,
         maar vóór een plaats: <i>Ik werk <b>niet</b>.</i> &nbsp; <i>Ik ga <b>niet</b> naar het werk.</i></p>`,
    items:[
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik heb geen auto.","Ik heb niet auto."], c:0,
        e:"Bij een zelfstandig naamwoord (auto) gebruik je <b>geen</b>: <i>Ik heb geen auto.</i>"},
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik werk niet.","Ik werk geen."], c:0,
        e:"Hier is geen zelfstandig naamwoord, dus <b>niet</b>: <i>Ik werk niet.</i>"},
      {kind:"herken",
        q:"Vul in: Ik drink ___ thee.",
        o:["geen","niet"], c:0,
        e:"Vóór een zelfstandig naamwoord (thee): <b>geen</b>. <i>Ik drink geen thee.</i>"},
      {kind:"herken",
        q:"Vul in: De koffie is ___ warm.",
        o:["niet","geen"], c:0,
        e:"Vóór een bijvoeglijk naamwoord (warm): <b>niet</b>. <i>De koffie is niet warm.</i>"},
      {kind:"herken", sentence:"Ik eet geen vlees.",
        parts:[["WIE","Ik"],["DOET","eet"],["WAT","geen vlees"]], ask:"WAT",
        e:"Wat eet je niet? <b>geen vlees</b>. 'geen' hoort bij het zelfstandig naamwoord."},
      {kind:"herken",
        q:"Waar staat 'niet' meestal in een korte zin?",
        o:["Achteraan","Vooraan","Op plek 2","Vlak na het onderwerp"], c:0,
        e:"<b>niet</b> staat meestal <b>achteraan</b>: <i>Ik werk niet.</i> (maar vóór een plaats: <i>Ik ga niet naar het werk.</i>)"},
      {kind:"bouw", tr:"Arabam yok.", model:"Ik heb geen auto.",
        answers:["ik heb geen auto"], words:["ik","heb (hebben)","geen auto"],
        e:"Bij een zelfstandig naamwoord: <b>geen</b>. <i>Ik heb geen auto.</i>"},
      {kind:"bouw", tr:"İşe gitmiyorum.", model:"Ik ga niet naar het werk.",
        answers:["ik ga niet naar het werk"], words:["ik","ga (gaan)","niet","naar het werk"],
        e:"<b>niet</b> vóór de plaats: <i>Ik ga niet naar het werk.</i>"},
      {kind:"bouw", tr:"Çay içmiyorum.", model:"Ik drink geen thee.",
        answers:["ik drink geen thee"], words:["ik","drink (drinken)","geen thee"],
        e:"Bij het zelfstandig naamwoord thee: <b>geen</b>. <i>Ik drink geen thee.</i>"},
    ],
  },
  {
    n:"Y7", num:"Les 7", t:"Grote mix: alles door elkaar", label:"Mix",
    desc:"Alle zinsopbouw uit les 1 t/m 6 in één les: herkennen, slepen, bouwen, vragen en nee zeggen — met nieuwe zinnen.",
    intro:`<h3>Alles door elkaar</h3>
      <p>In deze les komt <b>alles</b> uit les 1 t/m 6 terug: het onderwerp (WIE) en het werkwoord (DOET),
         de WAT, WAAR en WANNEER, zinnen <b>slepen</b>, zelf zinnen <b>bouwen</b>, een <b>vraag</b> maken en <b>nee</b> zeggen.</p>
      <div class="zin-legend"><span class="zrole r-wie">WIE</span><span class="zrole r-doet">DOET</span><span class="zrole r-wat">WAT</span><span class="zrole r-waar">WAAR</span><span class="zrole r-wanneer">WANNEER</span></div>
      <p>Onthoud de twee vaste regels: het werkwoord op <b>plek 2</b>, en <b>WANNEER vóór WAAR</b>.
         De zinnen zijn nieuw, maar het niveau is hetzelfde.</p>`,
    items:[
      {kind:"herken", sentence:"De man leest de krant.",
        parts:[["WIE","De man"],["DOET","leest"],["WAT","de krant"]], ask:"WIE",
        e:"Wie leest er? <b>De man</b>. Dat is de WIE."},
      {kind:"herken", sentence:"De meisjes zwemmen in het zwembad.",
        parts:[["WIE","De meisjes"],["DOET","zwemmen"],["WAAR","in het zwembad"]], ask:"DOET",
        e:"Het werkwoord staat op plek 2: <b>zwemmen</b>."},
      {kind:"herken", sentence:"Ik verkoop mijn oude fiets.",
        parts:[["WIE","Ik"],["DOET","verkoop"],["WAT","mijn oude fiets"]], ask:"WAT",
        e:"Wat verkoop je? <b>mijn oude fiets</b>. Dat is de WAT."},
      {kind:"herken", sentence:"De gast komt zondag.",
        parts:[["WIE","De gast"],["DOET","komt"],["WANNEER","zondag"]], ask:"WANNEER",
        e:"Wanneer komt de gast? <b>zondag</b>. Dat is de WANNEER (de tijd)."},
      {kind:"herken", sentence:"Wij lopen naar het park.",
        parts:[["WIE","Wij"],["DOET","lopen"],["WAAR","naar het park"]], ask:"WAAR",
        e:"Waar lopen jullie heen? <b>naar het park</b>. Dat is de WAAR (de plek)."},
      {kind:"herken",
        q:"Welke zin heeft de goede volgorde?",
        o:["Ik drink elke ochtend thee.","Ik elke ochtend drink thee."], c:0,
        e:"Het werkwoord (drink) hoort op plek 2: <b>Ik drink elke ochtend thee.</b>"},
      {kind:"sleep",
        parts:[["WIE","De gast"],["DOET","komt"],["WANNEER","zondag"],["WAAR","naar ons huis"]],
        e:"WANNEER vóór WAAR: <i>De gast komt zondag naar ons huis.</i>"},
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","koop"],["WAT","brood"],["WAAR","bij de bakker"]],
        e:"WIE → DOET → WAT → WAAR: <i>Ik koop brood bij de bakker.</i>"},
      {kind:"herken",
        q:"Welke zin is een goede vraag?",
        o:["Lees jij de krant?","Jij lees de krant?"], c:0,
        e:"In een ja/nee-vraag staat het werkwoord vooraan: <b>Lees jij de krant?</b>"},
      {kind:"herken",
        q:"Vul in: Ik heb ___ geld. (geen of niet?)",
        o:["geen","niet"], c:0,
        e:"Vóór een zelfstandig naamwoord (geld) gebruik je <b>geen</b>: <i>Ik heb geen geld.</i>"},
      {kind:"bouw", tr:"Misafir pazar günü geliyor.", model:"De gast komt zondag.",
        answers:["de gast komt zondag","zondag komt de gast"],
        words:["de gast","komt (komen)","zondag"],
        e:"WIE (De gast) → DOET (komt) → WANNEER (zondag)."},
      {kind:"bouw", tr:"Eski bisikletimi satıyorum.", model:"Ik verkoop mijn oude fiets.",
        answers:["ik verkoop mijn oude fiets"],
        words:["ik","verkoop (verkopen)","mijn oude fiets"],
        e:"WIE (Ik) → DOET (verkoop, plek 2) → WAT (mijn oude fiets)."},
      {kind:"bouw", tr:"Yarın parka gidiyorum.", model:"Ik ga morgen naar het park.",
        answers:["ik ga morgen naar het park","morgen ga ik naar het park"],
        words:["ik","ga (gaan)","morgen","naar het park"],
        e:"WANNEER vóór WAAR: <i>Ik ga morgen naar het park.</i>"},
    ],
  },
  {
    n:"Y8", num:"Les 8", t:"Een stap verder: omdraaien & langere zinnen", label:"Uitdaging",
    desc:"Iets moeilijker: begin met de tijd of plaats (het werkwoord blijft op plek 2), maak langere zinnen en open vragen.",
    intro:`<h3>Een stap verder</h3>
      <p>Je kent de gewone volgorde al. Nu draaien we de zin soms <b>om</b>: je begint met de <b>tijd</b> of de <b>plaats</b>.
         Dan blijft het werkwoord op <b>plek 2</b>, en het onderwerp (WIE) springt naar <b>ná</b> het werkwoord.</p>
      <div class="zin-legend"><span class="zrole r-wanneer">WANNEER</span><span class="zrole r-doet">DOET</span><span class="zrole r-wie">WIE</span><span class="zrole r-waar">WAAR</span></div>
      <p>✅ <i>Zaterdag ga ik naar de stad.</i> &nbsp; ❌ <i>Zaterdag ik ga naar de stad.</i></p>
      <p>Ook maak je nu <b>langere zinnen</b> met alle delen, en <b>open vragen</b> met een vraagwoord (waar, wanneer).</p>`,
    items:[
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Zaterdag ga ik naar de stad.","Zaterdag ik ga naar de stad."], c:0,
        e:"Begin je met de tijd, dan blijft het werkwoord op plek 2: <b>Zaterdag ga ik…</b> Het onderwerp (ik) komt ná het werkwoord."},
      {kind:"herken", sentence:"Vanavond komt de dokter.",
        parts:[["WANNEER","Vanavond"],["DOET","komt"],["WIE","de dokter"]], ask:"DOET",
        e:"Ook na de tijd staat het werkwoord op plek 2: <b>komt</b>."},
      {kind:"herken", sentence:"Vanavond komt de dokter.",
        parts:[["WANNEER","Vanavond"],["DOET","komt"],["WIE","de dokter"]], ask:"WIE",
        e:"Wie komt er? <b>de dokter</b>. In een omgedraaide zin komt het onderwerp ná het werkwoord."},
      {kind:"herken",
        q:"Je begint een zin met 'Zaterdag'. Waar staat het werkwoord dan?",
        o:["Nog steeds op plek 2","Op plek 1 (vooraan)","Helemaal achteraan"], c:0,
        e:"Het werkwoord blijft <b>altijd op plek 2</b>. Na 'Zaterdag' komt dus meteen het werkwoord, en dán het onderwerp."},
      {kind:"sleep",
        parts:[["WANNEER","Zaterdag"],["DOET","ga"],["WIE","ik"],["WAAR","naar het werk"]],
        e:"Begin met de tijd → werkwoord op plek 2, dan de WIE: <i>Zaterdag ga ik naar het werk.</i>"},
      {kind:"herken", sentence:"In de winkel koop ik brood.",
        parts:[["WAAR","In de winkel"],["DOET","koop"],["WIE","ik"],["WAT","brood"]], ask:"DOET",
        e:"Je begint hier met de plaats. Het werkwoord blijft op plek 2: <b>koop</b>."},
      {kind:"herken", sentence:"De vrouw koopt vandaag een nieuwe jas.",
        parts:[["WIE","De vrouw"],["DOET","koopt"],["WANNEER","vandaag"],["WAT","een nieuwe jas"]], ask:"WANNEER",
        e:"Wanneer koopt zij de jas? <b>vandaag</b>. Dat is de WANNEER."},
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","koop"],["WANNEER","zaterdag"],["WAT","brood"],["WAAR","bij de bakker"]],
        e:"Een langere zin met alle delen. WANNEER vóór WAAR: <i>Ik koop zaterdag brood bij de bakker.</i>"},
      {kind:"herken",
        q:"Welke vraag is goed?",
        o:["Waar werk jij?","Waar jij werkt?"], c:0,
        e:"Na een vraagwoord (waar) staat het werkwoord op plek 2: <b>Waar werk jij?</b>"},
      {kind:"bouw", tr:"Cumartesi şehre gidiyorum.", model:"Zaterdag ga ik naar de stad.",
        answers:["zaterdag ga ik naar de stad","ik ga zaterdag naar de stad"],
        words:["zaterdag","ga (gaan)","ik","naar de stad"],
        e:"Begin je met 'Zaterdag', dan komt het werkwoord (ga) meteen daarna, en dán 'ik'."},
      {kind:"bouw", tr:"Kadın bugün yeni bir ceket alıyor.", model:"De vrouw koopt vandaag een nieuwe jas.",
        answers:["de vrouw koopt vandaag een nieuwe jas","vandaag koopt de vrouw een nieuwe jas"],
        words:["de vrouw","koopt (kopen)","vandaag","een nieuwe jas"],
        e:"Een langere zin: WIE → DOET → WANNEER → WAT. Je mag ook met 'vandaag' beginnen."},
      {kind:"bouw", tr:"Nerede çalışıyorsun?", model:"Waar werk jij?",
        answers:["waar werk jij","waar werk je"],
        words:["waar","werk (werken)","jij"],
        e:"Een open vraag met een vraagwoord: <b>Waar</b> + werkwoord op plek 2 + WIE (jij)."},
    ],
  },
  {
    n:"Y9", num:"Les 9", t:"Twee werkwoorden: de rest gaat naar het eind", label:"Uitdaging+",
    desc:"Zinnen met willen, kunnen, moeten of gaan: het eerste werkwoord op plek 2, het tweede werkwoord (EIND) helemaal achteraan.",
    intro:`<h3>Twee werkwoorden in één zin</h3>
      <p>Soms staan er <b>twee werkwoorden</b> in een zin, bijvoorbeeld met <i>willen, kunnen, moeten</i> of <i>gaan</i>.
         Dan blijft het eerste werkwoord (DOET) op <b>plek 2</b>, en het <b>tweede werkwoord</b> springt helemaal naar het <b>eind</b>.</p>
      <div class="zin-legend"><span class="zrole r-wie">WIE</span><span class="zrole r-doet">DOET</span><span class="zrole r-wat">WAT</span><span class="zrole r-eind">EIND</span></div>
      <p>✅ <i>Ik wil een boek <b>lezen</b>.</i> &nbsp; ❌ <i>Ik wil lezen een boek.</i></p>
      <p>Het tweede werkwoord (lezen) staat dus <b>achteraan</b>. Alles wat erbij hoort — WAT, WAAR, WANNEER — komt ertussen.</p>`,
    items:[
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik wil een boek lezen.","Ik wil lezen een boek."], c:0,
        e:"Het tweede werkwoord (lezen) staat achteraan: <b>Ik wil een boek lezen.</b>"},
      {kind:"herken", sentence:"Ik wil een boek lezen.",
        parts:[["WIE","Ik"],["DOET","wil"],["WAT","een boek"],["EIND","lezen"]], ask:"EIND",
        e:"Het tweede werkwoord staat helemaal achteraan: <b>lezen</b>. Dat is de EIND."},
      {kind:"herken", sentence:"Ik wil een boek lezen.",
        parts:[["WIE","Ik"],["DOET","wil"],["WAT","een boek"],["EIND","lezen"]], ask:"DOET",
        e:"Het eerste werkwoord blijft op plek 2: <b>wil</b>."},
      {kind:"herken",
        q:"Waar staat het tweede werkwoord in een zin met twee werkwoorden?",
        o:["Achteraan (op het eind)","Op plek 2","Op plek 1 (vooraan)","Vlak na het onderwerp"], c:0,
        e:"Het tweede werkwoord springt naar het <b>eind</b> van de zin. Het eerste werkwoord blijft op plek 2."},
      {kind:"herken", sentence:"De kinderen moeten naar bed gaan.",
        parts:[["WIE","De kinderen"],["DOET","moeten"],["WAAR","naar bed"],["EIND","gaan"]], ask:"EIND",
        e:"Het tweede werkwoord staat achteraan: <b>gaan</b>."},
      {kind:"sleep",
        parts:[["WIE","Ik"],["DOET","wil"],["WAT","een boek"],["EIND","lezen"]],
        e:"Eerste werkwoord op plek 2, tweede werkwoord achteraan: <i>Ik wil een boek lezen.</i>"},
      {kind:"sleep",
        parts:[["WIE","Wij"],["DOET","gaan"],["WANNEER","vanavond"],["WAT","televisie"],["EIND","kijken"]],
        e:"Alles komt ertussen, 'kijken' achteraan: <i>Wij gaan vanavond televisie kijken.</i>"},
      {kind:"herken",
        q:"Welke zin is goed?",
        o:["Ik moet morgen de dokter bellen.","Ik moet bellen morgen de dokter."], c:0,
        e:"Het tweede werkwoord (bellen) staat achteraan: <b>Ik moet morgen de dokter bellen.</b>"},
      {kind:"bouw", tr:"Bir kitap okumak istiyorum.", model:"Ik wil een boek lezen.",
        answers:["ik wil een boek lezen"],
        words:["ik","wil (willen)","een boek","lezen"],
        e:"DOET (wil) op plek 2 → WAT (een boek) → EIND (lezen) achteraan."},
      {kind:"bouw", tr:"Yarın şehre gitmek istiyorum.", model:"Ik wil morgen naar de stad gaan.",
        answers:["ik wil morgen naar de stad gaan","morgen wil ik naar de stad gaan"],
        words:["ik","wil (willen)","morgen","naar de stad","gaan"],
        e:"'wil' op plek 2, WANNEER vóór WAAR, en 'gaan' helemaal achteraan."},
      {kind:"bouw", tr:"Doktoru aramam gerekiyor.", model:"Ik moet de dokter bellen.",
        answers:["ik moet de dokter bellen"],
        words:["ik","moet (moeten)","de dokter","bellen"],
        e:"DOET (moet) op plek 2 → WAT (de dokter) → EIND (bellen) achteraan."},
      {kind:"bouw", tr:"Bu akşam televizyon izlemek istiyoruz.", model:"Wij willen vanavond televisie kijken.",
        answers:["wij willen vanavond televisie kijken","we willen vanavond televisie kijken"],
        words:["wij","willen","vanavond","televisie","kijken"],
        e:"'willen' op plek 2 → WANNEER (vanavond) → WAT (televisie) → EIND (kijken) achteraan."},
    ],
  },
];
