/* ============================================================
   LESDATA — leerlijn en vragenbanken
   Dit bestand bevat alle inhoud van de cursus, los van de app-logica
   in index.html. Wordt vóór het hoofdscript geladen, dus COURSES, SOON
   en QUIZZES zijn daar gewoon beschikbaar.

   Een les toevoegen? Zet een regel in COURSES (tag "feat" optioneel) en
   voeg een blok toe in QUIZZES met hetzelfde lesnummer. De structuur:
     t = vraag, o = antwoorden, c = index van het juiste antwoord (0=eerste),
     e = uitleg, tag = vraagtype, tip = hint (optioneel, meestal een
     makkelijke voorbeeldzin met het woord).
   Optioneel (laten weg = niets te zien):
     img    = afbeelding bij de vraag (URL of pad, bijv. "images/trein.jpg").
     tipImg = afbeelding in het tip-vakje (handig om een woord in beeld uit te
              leggen). Voorbeeld: {tag:"…", t:"…", o:[…], c:0, e:"…",
              tip:"Kijk naar het plaatje.", tipImg:"images/hamer.jpg"}.
   Leerlingen kunnen elk Nederlands woord ook laten uitspreken (🔊-knop);
   dat werkt automatisch, daar hoef je niets voor in te stellen.
   Controleer met: node scripts/validate-lessons.js
   ============================================================ */
const COURSES = [
  {n:"1", t:"Nieuwe buren & verhuizen", desc:"Woorden uit thema 1: buren, huur, wijk, verhuizen."},
  {n:"2", t:"Marktplaats & spullen", desc:"Woorden over kopen, verkopen en spullen in huis."},
  {n:"3", t:"Op het station", desc:"Woorden over de trein, berichten en vertraging."},
  {n:"4", t:"Reizen & OV-chipkaart", desc:"Woorden over pinnen, opladen en veilig reizen."},
  {n:"5", t:"Contact met de buren", desc:"Woorden over gasten, feest en samenwonen.", bookmark:true},
  {n:"6", t:"Het huis beschrijven", desc:"Woorden over vorm, maat en materiaal."},
  {n:"7", t:"Grote mix: les 1 t/m 6", desc:"Alle thema's door elkaar. Herhaal en test wat je geleerd hebt.", feat:true},
];
const SOON = [
  {n:"9", t:"Voorzetsels (in, op, onder)"},{n:"10", t:"Bijvoeglijke naamwoorden"},
  {n:"11", t:"Leestekens & hoofdletters"},
];

/* ---------------- vragenbanken ---------------- */
const QUIZZES = {
  "1":{ title:"Nieuwe buren & verhuizen", sub:"Lees het woord. Kies het goede antwoord. Bij elke vraag zie je ook het Turkse woord (Türkçe) als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent het woord <span class='m'>de buren</span>?", o:["komşular","misafir","aile","arkadaş"], c:0,
      e:"<b>de buren</b> = komşular. Dat zijn de mensen die naast je wonen.",
      tip:"In een zin: <i>De <b>buren</b> wonen naast ons huis.</i> Het gaat dus over de mensen die naast je wonen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de buurman</span>?", o:["komşu (erkek)","misafir","aile","arkadaş"], c:0,
      e:"<b>de buurman</b> = (erkek) komşu. De man die naast je woont. De vrouw is <i>de buurvrouw</i>.",
      tip:"In een zin: <i>De <b>buurman</b> is een man die naast je woont.</i> Denk aan 'man' in het woord."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verhuizen</span>?", o:["taşınmak","temizlemek","satın almak","aramak"], c:0,
      e:"<b>verhuizen</b> = taşınmak. Je gaat in een ander huis wonen. Voorbeeld: <i>Wij verhuizen naar een nieuw huis.</i>",
      tip:"In een zin: <i>Wij <b>verhuizen</b> naar een nieuw huis.</i> Je gaat dus ergens anders wonen."},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>komşular</span> (de mensen naast je)?", o:["de buren","de gast","de wijk","de hulp"], c:0,
      e:"komşular = <b>de buren</b>. 'de gast' = misafir, 'de wijk' = mahalle.",
      tip:"Denk aan de mensen die vlak naast jou wonen. Welk Nederlands woord hoort daarbij?"},
    {tag:"de of het", t:"Wat is goed: <span class='m'>___ huis</span>?", o:["het huis","de huis","een huizen","dat huizen"], c:0,
      e:"Het is <b>het huis</b>. Dit woord krijgt 'het'. Deze woorden leer je uit je hoofd.",
      tip:"Zeg hardop: '... huis'. Dit woord hoort bij de kleinere groep 'het'-woorden.", tipImg:"images/huis.svg"},
    {tag:"de of het", t:"Wat is goed: <span class='m'>___ wijk</span> (mahalle)?", o:["de wijk","het wijk","een wijken","die wijken"], c:0,
      e:"Het is <b>de wijk</b> = mahalle. De meeste woorden krijgen 'de'.",
      tip:"Een buurt in de stad. De meeste woorden krijgen 'de' — welk lidwoord past hier?"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de huur</span>?", o:["kira","fiyat","ev","oda"], c:0,
      e:"<b>de huur</b> = kira. Dat is het geld dat je elke maand voor je huis betaalt.",
      tip:"In een zin: <i>Elke maand betaal ik de <b>huur</b> voor mijn huis.</i> Het gaat om geld voor je woning."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het adres</span>?", o:["adres","isim","şehir","numara"], c:0,
      e:"<b>het adres</b> = adres. Straat, huisnummer en plaats waar je woont. Let op: het is 'het adres'.",
      tip:"In een zin: <i>Op de brief staat mijn <b>adres</b>: straat, nummer en plaats.</i>"},
    {tag:"Werkwoord", t:"Welke zin is goed? <span class='m'>Gisteren ___ wij naar een nieuw huis. (verhuizen)</span>", o:["verhuisden","verhuizen","verhuis","verhuist"], c:0,
      e:"Verleden tijd: <b>verhuisden</b>. Nu = wij verhuizen, gisteren = wij verhuisden.",
      tip:"'Gisteren' betekent verleden tijd. Nu = wij verhuizen; welke vorm past bij gisteren?"},
  ]},
  "2":{ title:"Marktplaats & spullen", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de advertentie</span>?", o:["reklam / ilan","fiyat","dükkan","hediye"], c:0,
      e:"<b>de advertentie</b> = ilan/reklam. Bijvoorbeeld op Marktplaats zet je een advertentie om iets te verkopen.",
      tip:"In een zin: <i>Ik zet een <b>advertentie</b> op Marktplaats om mijn bank te verkopen.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verkopen</span>?", o:["satmak","almak","bakmak","aramak"], c:0,
      e:"<b>verkopen</b> = satmak. Het tegenovergestelde is 'kopen' (satın almak).",
      tip:"In een zin: <i>Ik wil mijn oude fiets <b>verkopen</b> voor 20 euro.</i> Het is het tegenovergestelde van kopen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>bieden</span>?", o:["teklif vermek","ödemek","göndermek","sormak"], c:0,
      e:"<b>bieden</b> = teklif vermek. Voorbeeld: <i>Ik bied 10 euro voor de stoel.</i>",
      tip:"In een zin: <i>Ik <b>bied</b> 10 euro voor de stoel.</i> Je zegt hoeveel je wilt betalen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>hout</span> (houten)?", o:["tahta / ahşap","cam","demir","yün"], c:0,
      e:"<b>hout</b> = tahta. Een houten tafel = ahşap masa.",
      tip:"In een zin: <i>De tafel is van <b>hout</b>.</i> Denk aan een boom.", tipImg:"images/hout.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>wol</span> (wollen)?", o:["yün","pamuk","deri","plastik"], c:0,
      e:"<b>wol</b> = yün. Een wollen trui = yün kazak.",
      tip:"In een zin: <i>Een <b>wollen</b> trui is lekker warm.</i> Het komt van een schaap.", tipImg:"images/wol.svg"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>halı</span>?", o:["het kleed","de spiegel","de knop","de hamer"], c:0,
      e:"halı = <b>het kleed</b>. Let op: het is 'het kleed'.",
      tip:"Denk aan iets zachts dat op de vloer ligt. Welk Nederlands woord hoort daarbij?", tipImg:"images/kleed.svg"},
    {tag:"Tegenstelling", t:"Wat past bij <span class='m'>rond</span> (yuvarlak)? Kies het tegenovergestelde.", o:["vierkant","breed","zwaar","laag"], c:0,
      e:"<b>rond</b> = yuvarlak, <b>vierkant</b> = kare. Dat zijn tegenovergestelde vormen.",
      tip:"Een bal is rond. Wat is de vorm met vier rechte hoeken, zoals een doos?"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opsturen</span>?", o:["göndermek","almak","yırtmak","saklamak"], c:0,
      e:"<b>opsturen</b> = göndermek. Voorbeeld: <i>Ik stuur het pakket op met de post.</i>",
      tip:"In een zin: <i>Ik <b>stuur</b> het pakket <b>op</b> met de post.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>zwaar</span>?", o:["ağır","hafif","geniş","dar"], c:0,
      e:"<b>zwaar</b> = ağır. Het tegenovergestelde is 'licht' (hafif).",
      tip:"In een zin: <i>De doos is heel <b>zwaar</b>, ik kan hem bijna niet tillen.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>breed</span>?", o:["geniş","dar","yüksek","alçak"], c:0,
      e:"<b>breed</b> = geniş. Het tegenovergestelde is 'smal' (dar).",
      tip:"In een zin: <i>De kast is te <b>breed</b> voor deze muur.</i> Het gaat over de breedte."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>tweedehands</span>?", o:["ikinci el","yeni","pahalı","bedava"], c:0,
      e:"<b>tweedehands</b> = ikinci el. Iemand heeft het al gebruikt. Voorbeeld: <i>Ik koop een tweedehands bank.</i>",
      tip:"In een zin: <i>Ik koop een <b>tweedehands</b> bank; iemand gebruikte hem al.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>ayna</span>?", o:["de spiegel","het kleed","de hamer","de knop"], c:0,
      e:"ayna = <b>de spiegel</b>. In de spiegel zie je jezelf. 'het kleed' = halı, 'de hamer' = çekiç.",
      tip:"Denk aan het glas waarin je jezelf ziet. Welk Nederlands woord hoort daarbij?", tipImg:"images/spiegel.svg"},
  ]},
  "3":{ title:"Op het station", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de automaat</span>?", o:["makine / otomat","tren","bilet","kapı"], c:0,
      e:"<b>de automaat</b> = makine/otomat. Bij de automaat op het station koop je een kaartje.",
      tip:"In een zin: <i>Bij de <b>automaat</b> koop ik een kaartje.</i> Het is een machine.", tipImg:"images/automaat.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het bericht</span>?", o:["mesaj","ses","kağıt","resim"], c:0,
      e:"<b>het bericht</b> = mesaj. Voorbeeld: <i>Ik krijg een bericht op mijn telefoon.</i>",
      tip:"In een zin: <i>Ik krijg een <b>bericht</b> op mijn telefoon.</i> Zoals een appje of sms."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>handig</span>?", o:["kullanışlı / pratik","zor","pahalı","tehlikeli"], c:0,
      e:"<b>handig</b> = kullanışlı. Iets dat makkelijk is om te gebruiken.",
      tip:"In een zin: <i>Deze app is heel <b>handig</b>, hij helpt me snel.</i> Dus makkelijk in gebruik."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het lawaai</span>?", o:["gürültü","müzik","sessizlik","haber"], c:0,
      e:"<b>het lawaai</b> = gürültü. Veel hard geluid.",
      tip:"In een zin: <i>Er is veel <b>lawaai</b> op straat; ik kan niets horen.</i> Veel hard geluid."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hulp</span>?", o:["yardım","soru","zaman","yol"], c:0,
      e:"<b>de hulp</b> = yardım. Werkwoord: helpen = yardım etmek.",
      tip:"In een zin: <i>Bedankt voor je <b>hulp</b>!</i> Denk aan het werkwoord 'helpen'."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>ergens</span>?", o:["bir yerde","hiçbir yerde","her zaman","şimdi"], c:0,
      e:"<b>ergens</b> = bir yerde. Voorbeeld: <i>Mijn kaartje ligt ergens in mijn tas.</i>",
      tip:"In een zin: <i>Mijn kaartje ligt <b>ergens</b> in mijn tas.</i> Op een plek, maar je weet niet precies waar."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de vertraging</span>?", o:["gecikme","varış","hız","durak"], c:0,
      e:"<b>de vertraging</b> = gecikme. De trein komt later dan normaal.",
      tip:"In een zin: <i>De trein heeft <b>vertraging</b> en komt tien minuten later.</i>", tipImg:"images/trein.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>op tijd</span>?", o:["zamanında","geç","erken","asla"], c:0,
      e:"<b>op tijd</b> = zamanında. Niet te laat en niet te vroeg.",
      tip:"In een zin: <i>De trein is <b>op tijd</b>: niet te laat en niet te vroeg.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>duidelijk</span>?", o:["açık (net anlaşılır)","zor","yavaş","sessiz"], c:0,
      e:"<b>duidelijk</b> = açık / net. Je snapt het meteen. Voorbeeld: <i>Het bericht op het bord is duidelijk.</i>",
      tip:"In een zin: <i>Het bord is <b>duidelijk</b>, ik snap het meteen.</i>"},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ bericht</span>", o:["het bericht","de bericht","een berichten","die berichten"], c:0,
      e:"Het is <b>het bericht</b>. Dit woord krijgt 'het'.",
      tip:"Zeg hardop: '... bericht'. Dit woord hoort bij de groep 'het'-woorden."},
  ]},
  "4":{ title:"Reizen & OV-chipkaart", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opladen</span>?", o:["şarj etmek","kapatmak","satmak","kırmak"], c:0,
      e:"<b>opladen</b> = şarj etmek. Je laadt je OV-chipkaart of je telefoon op.",
      tip:"In een zin: <i>Ik moet mijn OV-chipkaart <b>opladen</b> voordat ik reis.</i> Ook je telefoon doe je zo."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pinpas</span>?", o:["banka kartı","para","cüzdan","fatura"], c:0,
      e:"<b>de pinpas</b> = banka kartı. Hiermee betaal je in de winkel.",
      tip:"In een zin: <i>Ik betaal in de winkel met mijn <b>pinpas</b>.</i> Een kaart van de bank.", tipImg:"images/pinpas.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pincode</span>?", o:["pin kodu / şifre","adres","isim","numara"], c:0,
      e:"<b>de pincode</b> = pin kodu. De geheime cijfers van je pinpas.",
      tip:"In een zin: <i>Ik typ mijn geheime <b>pincode</b> in bij de automaat.</i> De cijfers van je pas."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het scherm</span>?", o:["ekran","tuş","kart","ses"], c:0,
      e:"<b>het scherm</b> = ekran. Bijvoorbeeld het scherm van de automaat of je telefoon.",
      tip:"In een zin: <i>Op het <b>scherm</b> van de automaat lees je de tekst.</i>", tipImg:"images/scherm.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>veilig</span>?", o:["güvenli","tehlikeli","hızlı","yavaş"], c:0,
      e:"<b>veilig</b> = güvenli. Het tegenovergestelde is 'gevaarlijk' (tehlikeli).",
      tip:"In een zin: <i>Bewaar je pincode <b>veilig</b>, dan kan niemand hem stelen.</i> Niet gevaarlijk."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de knop</span>?", o:["düğme / tuş","kapı","yol","ekran"], c:0,
      e:"<b>de knop</b> = düğme/tuş. Je drukt op de knop.",
      tip:"In een zin: <i>Druk op de groene <b>knop</b> om te beginnen.</i>", tipImg:"images/knop.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>drukken op</span>?", o:["basmak","çekmek","tutmak","atmak"], c:0,
      e:"<b>drukken op</b> = basmak. Voorbeeld: <i>Druk op de groene knop.</i>",
      tip:"In een zin: <i>Je moet met je vinger op de knop <b>drukken</b>.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>minimaal</span>?", o:["en az","en çok","bazen","hemen"], c:0,
      e:"<b>minimaal</b> = en az. Voorbeeld: <i>Je hebt minimaal 4 euro nodig.</i>",
      tip:"In een zin: <i>Je hebt <b>minimaal</b> 4 euro nodig: minder mag niet.</i> Dus 'ten minste'."},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ scherm</span>", o:["het scherm","de scherm","een schermen","dat schermen"], c:0,
      e:"Het is <b>het scherm</b>. Dit woord krijgt 'het'.",
      tip:"Zeg hardop: '... scherm'. Dit woord hoort bij de groep 'het'-woorden."},
  ]},
  "5":{ title:"Contact met de buren", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>boos</span>?", o:["kızgın","mutlu","yorgun","üzgün"], c:0,
      e:"<b>boos</b> = kızgın. Voorbeeld: <i>De buurman is boos om het lawaai.</i>",
      tip:"In een zin: <i>De buurman is <b>boos</b> om het lawaai.</i> Hij is niet blij."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de gast</span>?", o:["misafir","komşu","aile","çocuk"], c:0,
      e:"<b>de gast</b> = misafir. Iemand die bij je op bezoek komt.",
      tip:"In een zin: <i>Vanavond komt er een <b>gast</b> eten.</i> Iemand op bezoek."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>moe</span>?", o:["yorgun","kızgın","mutlu","hasta"], c:0,
      e:"<b>moe</b> = yorgun. Voorbeeld: <i>Ik ben moe na het verhuizen.</i>",
      tip:"In een zin: <i>Na het verhuizen ben ik heel <b>moe</b>.</i> Je wilt slapen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>overmorgen</span>?", o:["öbür gün","dün","bugün","her gün"], c:0,
      e:"<b>overmorgen</b> = öbür gün (yarından sonraki gün). Vandaag → morgen → overmorgen.",
      tip:"Denk aan: vandaag → morgen → <b>overmorgen</b>. Dus over twee dagen."},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>hard</span> (sert / yüksek sesli)?", o:["zacht","stil","boos","moe"], c:0,
      e:"<b>hard</b> ↔ <b>zacht</b> (yumuşak / hafif). 'zacht' betekent ook: niet luid.",
      tip:"Een kussen is niet hard, maar juist ...? Denk aan het tegenovergestelde."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>stil</span>?", o:["sessiz","gürültülü","hızlı","güvenli"], c:0,
      e:"<b>stil</b> = sessiz. Het tegenovergestelde van lawaai.",
      tip:"In een zin: <i>'s Nachts is het <b>stil</b> in de straat.</i> Geen geluid, geen lawaai."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de leeftijd</span>?", o:["yaş","isim","adres","boy"], c:0,
      e:"<b>de leeftijd</b> = yaş. Voorbeeld: <i>Wat is de leeftijd van je kind?</i>",
      tip:"In een zin: <i>Wat is de <b>leeftijd</b> van je kind?</i> Hoeveel jaar iemand is."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de verjaardag</span>?", o:["doğum günü","davetiye","tatil","bayram"], c:0,
      e:"<b>de verjaardag</b> = doğum günü. Op je verjaardag word je een jaar ouder.",
      tip:"In een zin: <i>Op mijn <b>verjaardag</b> word ik een jaar ouder.</i>", tipImg:"images/taart.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>oppassen</span>?", o:["göz kulak olmak","uyumak","oynamak","beklemek"], c:0,
      e:"<b>oppassen</b> = göz kulak olmak. Voorbeeld: <i>Ik pas op de kinderen van de buren.</i>",
      tip:"In een zin: <i>Ik <b>pas op</b> de kinderen van de buren.</i> Je let goed op ze."},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>davetiye</span>?", o:["de uitnodiging","de verjaardag","het gesprek","de gast"], c:0,
      e:"davetiye = <b>de uitnodiging</b>. Je krijgt een uitnodiging voor een feest. 'de verjaardag' = doğum günü.",
      tip:"Denk aan wat je krijgt als je naar een feest mag komen. Welk Nederlands woord hoort daarbij?"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vieren</span>?", o:["kutlamak","çalışmak","beklemek","taşınmak"], c:0,
      e:"<b>vieren</b> = kutlamak. Voorbeeld: <i>Wij vieren mijn verjaardag met de buren.</i>",
      tip:"In een zin: <i>Wij <b>vieren</b> mijn verjaardag met taart.</i> Iets leuks samen doen."},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ gesprek</span> (konuşma)", o:["het gesprek","de gesprek","een gesprekken","die gesprekken"], c:0,
      e:"Het is <b>het gesprek</b>. Dit woord krijgt 'het'.",
      tip:"Zeg hardop: '... gesprek'. Dit woord hoort bij de groep 'het'-woorden."},
  ]},
  "6":{ title:"Het huis beschrijven", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>modern</span>?", o:["modern / yeni tarz","eski","küçük","ucuz"], c:0,
      e:"<b>modern</b> = modern. Het tegenovergestelde is 'ouderwets' (eski).",
      tip:"In een zin: <i>Het huis is <b>modern</b>: nieuw en van deze tijd.</i> Niet ouderwets."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>ruim</span>?", o:["geniş / ferah","dar","karanlık","dolu"], c:0,
      e:"<b>ruim</b> = geniş/ferah. Er is veel plek. Voorbeeld: <i>Een ruime kamer.</i>",
      tip:"In een zin: <i>De kamer is lekker <b>ruim</b>: er is veel plek.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vierkant</span>?", o:["kare","yuvarlak","üçgen","uzun"], c:0,
      e:"<b>vierkant</b> = kare. Een vorm met vier gelijke kanten.",
      tip:"Denk aan een vorm met vier gelijke, rechte kanten, zoals een dobbelsteen.", tipImg:"images/vierkant.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de meter</span>?", o:["metre","kilo","litre","saat"], c:0,
      e:"<b>de meter</b> = metre. Je meet lengte in meters. 100 cm = 1 meter.",
      tip:"In een zin: <i>De kamer is drie <b>meter</b> breed.</i> 100 cm = 1 hiervan.", tipImg:"images/meter.svg"},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>laag</span> (alçak)?", o:["hoog","breed","rond","licht"], c:0,
      e:"<b>laag</b> = alçak, <b>hoog</b> = yüksek. Dat zijn tegenovergestelden.",
      tip:"Een tafel is laag, maar een flat is juist ...? Denk ver naar boven."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hamer</span>?", o:["çekiç","testere","vida","merdiven"], c:0,
      e:"<b>de hamer</b> = çekiç. Gereedschap om te timmeren.",
      tip:"In een zin: <i>Met een <b>hamer</b> sla ik een spijker in de muur.</i> Gereedschap.", tipImg:"images/hamer.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>licht</span>?", o:["hafif / aydınlık","ağır","karanlık","sıcak"], c:0,
      e:"<b>licht</b> heeft twee betekenissen: hafif (niet zwaar) én aydınlık/ışık. Tegenovergestelde van zwaar én van donker.",
      tip:"In een zin: <i>De tas is <b>licht</b> (niet zwaar) en de kamer is <b>licht</b> (niet donker).</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>rond</span>?", o:["yuvarlak","kare","düz","köşeli"], c:0,
      e:"<b>rond</b> = yuvarlak. Zoals een bal of een bord.",
      tip:"Denk aan de vorm van een bal of een bord: zonder hoeken.", tipImg:"images/rond.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>breed</span>?", o:["geniş","dar","yüksek","kısa"], c:0,
      e:"<b>breed</b> = geniş. Het tegenovergestelde is 'smal' (dar).",
      tip:"In een zin: <i>De kast is te <b>breed</b> voor deze muur.</i> Het gaat over de breedte."},
  ]},
  "7":{ title:"Grote mix: les 1 t/m 6", sub:"Alle thema's uit les 1 t/m 6 door elkaar. Türkçe woord staat erbij als hulp. Elke keer in andere volgorde.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent het woord <span class='m'>de buren</span>?", o:["komşular","misafir","aile","arkadaş"], c:0,
      e:"<b>de buren</b> = komşular. Dat zijn de mensen die naast je wonen.",
      tip:"In een zin: <i>De <b>buren</b> wonen naast ons huis.</i> Het gaat over de mensen die naast je wonen."},
    {tag:"Werkwoord", t:"Welke zin is goed? <span class='m'>Gisteren ___ wij naar een nieuw huis. (verhuizen)</span>", o:["verhuisden","verhuizen","verhuis","verhuist"], c:0,
      e:"Verleden tijd: <b>verhuisden</b>. Nu = wij verhuizen, gisteren = wij verhuisden.",
      tip:"'Gisteren' betekent verleden tijd. Nu = wij verhuizen; welke vorm past bij gisteren?"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verkopen</span>?", o:["satmak","almak","bakmak","aramak"], c:0,
      e:"<b>verkopen</b> = satmak. Het tegenovergestelde is 'kopen' (satın almak).",
      tip:"In een zin: <i>Ik wil mijn oude fiets <b>verkopen</b> voor 20 euro.</i> Het tegenovergestelde van kopen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>tweedehands</span>?", o:["ikinci el","yeni","pahalı","bedava"], c:0,
      e:"<b>tweedehands</b> = ikinci el. Iemand heeft het al gebruikt. Voorbeeld: <i>Ik koop een tweedehands bank.</i>",
      tip:"In een zin: <i>Ik koop een <b>tweedehands</b> bank; iemand gebruikte hem al.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>ayna</span>?", o:["de spiegel","het kleed","de hamer","de knop"], c:0,
      e:"ayna = <b>de spiegel</b>. In de spiegel zie je jezelf. 'het kleed' = halı, 'de hamer' = çekiç.",
      tip:"Denk aan het glas waarin je jezelf ziet. Welk Nederlands woord hoort daarbij?", tipImg:"images/spiegel.svg"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de vertraging</span>?", o:["gecikme","varış","hız","durak"], c:0,
      e:"<b>de vertraging</b> = gecikme. De trein komt later dan normaal.",
      tip:"In een zin: <i>De trein heeft <b>vertraging</b> en komt tien minuten later.</i>", tipImg:"images/trein.svg"},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ bericht</span>", o:["het bericht","de bericht","een berichten","die berichten"], c:0,
      e:"Het is <b>het bericht</b>. Dit woord krijgt 'het'.",
      tip:"Zeg hardop: '... bericht'. Dit woord hoort bij de groep 'het'-woorden."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opladen</span>?", o:["şarj etmek","kapatmak","satmak","kırmak"], c:0,
      e:"<b>opladen</b> = şarj etmek. Je laadt je OV-chipkaart of je telefoon op.",
      tip:"In een zin: <i>Ik moet mijn OV-chipkaart <b>opladen</b> voordat ik reis.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pincode</span>?", o:["pin kodu / şifre","adres","isim","numara"], c:0,
      e:"<b>de pincode</b> = pin kodu. De geheime cijfers van je pinpas.",
      tip:"In een zin: <i>Ik typ mijn geheime <b>pincode</b> in bij de automaat.</i> De cijfers van je pas."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>veilig</span>?", o:["güvenli","tehlikeli","hızlı","yavaş"], c:0,
      e:"<b>veilig</b> = güvenli. Het tegenovergestelde is 'gevaarlijk' (tehlikeli).",
      tip:"In een zin: <i>Bewaar je pincode <b>veilig</b>, dan kan niemand hem stelen.</i> Niet gevaarlijk."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>boos</span>?", o:["kızgın","mutlu","yorgun","üzgün"], c:0,
      e:"<b>boos</b> = kızgın. Voorbeeld: <i>De buurman is boos om het lawaai.</i>",
      tip:"In een zin: <i>De buurman is <b>boos</b> om het lawaai.</i> Hij is niet blij."},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>davetiye</span>?", o:["de uitnodiging","de verjaardag","het gesprek","de gast"], c:0,
      e:"davetiye = <b>de uitnodiging</b>. Je krijgt een uitnodiging voor een feest. 'de verjaardag' = doğum günü.",
      tip:"Denk aan wat je krijgt als je naar een feest mag komen. Welk Nederlands woord hoort daarbij?"},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>hard</span> (sert / yüksek sesli)?", o:["zacht","stil","boos","moe"], c:0,
      e:"<b>hard</b> ↔ <b>zacht</b> (yumuşak / hafif). 'zacht' betekent ook: niet luid.",
      tip:"Een kussen is niet hard, maar juist ...? Denk aan het tegenovergestelde."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vierkant</span>?", o:["kare","yuvarlak","üçgen","uzun"], c:0,
      e:"<b>vierkant</b> = kare. Een vorm met vier gelijke kanten.",
      tip:"Denk aan een vorm met vier gelijke, rechte kanten, zoals een dobbelsteen.", tipImg:"images/vierkant.svg"},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>laag</span> (alçak)?", o:["hoog","breed","rond","licht"], c:0,
      e:"<b>laag</b> = alçak, <b>hoog</b> = yüksek. Dat zijn tegenovergestelden.",
      tip:"Een tafel is laag, maar een flat is juist ...? Denk ver naar boven."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hamer</span>?", o:["çekiç","testere","vida","merdiven"], c:0,
      e:"<b>de hamer</b> = çekiç. Gereedschap om te timmeren.",
      tip:"In een zin: <i>Met een <b>hamer</b> sla ik een spijker in de muur.</i> Gereedschap.", tipImg:"images/hamer.svg"},
  ]},
};
