/* ============================================================
   LESDATA — leerlijn en vragenbanken
   Dit bestand bevat alle inhoud van de cursus, los van de app-logica
   in index.html. Wordt vóór het hoofdscript geladen, dus COURSES, SOON
   en QUIZZES zijn daar gewoon beschikbaar.

   Een les toevoegen? Zet een regel in COURSES (tag "feat" optioneel) en
   voeg een blok toe in QUIZZES met hetzelfde lesnummer. De structuur:
     t = vraag, o = antwoorden, c = index van het juiste antwoord (0=eerste),
     e = uitleg, tag = vraagtype.
   Controleer met: node scripts/validate-lessons.js
   ============================================================ */
const COURSES = [
  {n:"1", t:"Nieuwe buren & verhuizen", desc:"Woorden uit thema 1: buren, huur, wijk, verhuizen."},
  {n:"2", t:"Marktplaats & spullen", desc:"Woorden over kopen, verkopen en spullen in huis."},
  {n:"3", t:"Op het station", desc:"Woorden over de trein, berichten en vertraging."},
  {n:"4", t:"Reizen & OV-chipkaart", desc:"Woorden over pinnen, opladen en veilig reizen."},
  {n:"5", t:"Contact met de buren", desc:"Woorden over gasten, feest en samenwonen.", bookmark:true},
  {n:"6", t:"Het huis beschrijven", desc:"Woorden over vorm, maat en materiaal."},
  {n:"7", t:"Grote mix: les 1 t/m 6", desc:"Alle thema's door elkaar. Herhaal en test wat je geleerd hebt.", feat:true},
];
const SOON = [
  {n:"9", t:"Voorzetsels (in, op, onder)"},{n:"10", t:"Bijvoeglijke naamwoorden"},
  {n:"11", t:"Leestekens & hoofdletters"},
];

/* ---------------- vragenbanken ---------------- */
const QUIZZES = {
  "1":{ title:"Nieuwe buren & verhuizen", sub:"Lees het woord. Kies het goede antwoord. Bij elke vraag zie je ook het Turkse woord (Türkçe) als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent het woord <span class='m'>de buren</span>?", o:["komşular","misafir","aile","arkadaş"], c:0,
      e:"<b>de buren</b> = komşular. Dat zijn de mensen die naast je wonen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de buurman</span>?", o:["komşu (erkek)","misafir","aile","arkadaş"], c:0,
      e:"<b>de buurman</b> = (erkek) komşu. De man die naast je woont. De vrouw is <i>de buurvrouw</i>."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verhuizen</span>?", o:["taşınmak","temizlemek","satın almak","aramak"], c:0,
      e:"<b>verhuizen</b> = taşınmak. Je gaat in een ander huis wonen. Voorbeeld: <i>Wij verhuizen naar een nieuw huis.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>komşular</span> (de mensen naast je)?", o:["de buren","de gast","de wijk","de hulp"], c:0,
      e:"komşular = <b>de buren</b>. 'de gast' = misafir, 'de wijk' = mahalle."},
    {tag:"de of het", t:"Wat is goed: <span class='m'>___ huis</span>?", o:["het huis","de huis","een huizen","dat huizen"], c:0,
      e:"Het is <b>het huis</b>. Dit woord krijgt 'het'. Deze woorden leer je uit je hoofd."},
    {tag:"de of het", t:"Wat is goed: <span class='m'>___ wijk</span> (mahalle)?", o:["de wijk","het wijk","een wijken","die wijken"], c:0,
      e:"Het is <b>de wijk</b> = mahalle. De meeste woorden krijgen 'de'."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de huur</span>?", o:["kira","fiyat","ev","oda"], c:0,
      e:"<b>de huur</b> = kira. Dat is het geld dat je elke maand voor je huis betaalt."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het adres</span>?", o:["adres","isim","şehir","numara"], c:0,
      e:"<b>het adres</b> = adres. Straat, huisnummer en plaats waar je woont. Let op: het is 'het adres'."},
    {tag:"Werkwoord", t:"Welke zin is goed? <span class='m'>Gisteren ___ wij naar een nieuw huis. (verhuizen)</span>", o:["verhuisden","verhuizen","verhuis","verhuist"], c:0,
      e:"Verleden tijd: <b>verhuisden</b>. Nu = wij verhuizen, gisteren = wij verhuisden."},
  ]},
  "2":{ title:"Marktplaats & spullen", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de advertentie</span>?", o:["reklam / ilan","fiyat","dükkan","hediye"], c:0,
      e:"<b>de advertentie</b> = ilan/reklam. Bijvoorbeeld op Marktplaats zet je een advertentie om iets te verkopen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verkopen</span>?", o:["satmak","almak","bakmak","aramak"], c:0,
      e:"<b>verkopen</b> = satmak. Het tegenovergestelde is 'kopen' (satın almak)."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>bieden</span>?", o:["teklif vermek","ödemek","göndermek","sormak"], c:0,
      e:"<b>bieden</b> = teklif vermek. Voorbeeld: <i>Ik bied 10 euro voor de stoel.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>hout</span> (houten)?", o:["tahta / ahşap","cam","demir","yün"], c:0,
      e:"<b>hout</b> = tahta. Een houten tafel = ahşap masa."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>wol</span> (wollen)?", o:["yün","pamuk","deri","plastik"], c:0,
      e:"<b>wol</b> = yün. Een wollen trui = yün kazak."},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>halı</span>?", o:["het kleed","de spiegel","de knop","de hamer"], c:0,
      e:"halı = <b>het kleed</b>. Let op: het is 'het kleed'."},
    {tag:"Tegenstelling", t:"Wat past bij <span class='m'>rond</span> (yuvarlak)? Kies het tegenovergestelde.", o:["vierkant","breed","zwaar","laag"], c:0,
      e:"<b>rond</b> = yuvarlak, <b>vierkant</b> = kare. Dat zijn tegenovergestelde vormen."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opsturen</span>?", o:["göndermek","almak","yırtmak","saklamak"], c:0,
      e:"<b>opsturen</b> = göndermek. Voorbeeld: <i>Ik stuur het pakket op met de post.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>zwaar</span>?", o:["ağır","hafif","geniş","dar"], c:0,
      e:"<b>zwaar</b> = ağır. Het tegenovergestelde is 'licht' (hafif)."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>breed</span>?", o:["geniş","dar","yüksek","alçak"], c:0,
      e:"<b>breed</b> = geniş. Het tegenovergestelde is 'smal' (dar)."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>tweedehands</span>?", o:["ikinci el","yeni","pahalı","bedava"], c:0,
      e:"<b>tweedehands</b> = ikinci el. Iemand heeft het al gebruikt. Voorbeeld: <i>Ik koop een tweedehands bank.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>ayna</span>?", o:["de spiegel","het kleed","de hamer","de knop"], c:0,
      e:"ayna = <b>de spiegel</b>. In de spiegel zie je jezelf. 'het kleed' = halı, 'de hamer' = çekiç."},
  ]},
  "3":{ title:"Op het station", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de automaat</span>?", o:["makine / otomat","tren","bilet","kapı"], c:0,
      e:"<b>de automaat</b> = makine/otomat. Bij de automaat op het station koop je een kaartje."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het bericht</span>?", o:["mesaj","ses","kağıt","resim"], c:0,
      e:"<b>het bericht</b> = mesaj. Voorbeeld: <i>Ik krijg een bericht op mijn telefoon.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>handig</span>?", o:["kullanışlı / pratik","zor","pahalı","tehlikeli"], c:0,
      e:"<b>handig</b> = kullanışlı. Iets dat makkelijk is om te gebruiken."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het lawaai</span>?", o:["gürültü","müzik","sessizlik","haber"], c:0,
      e:"<b>het lawaai</b> = gürültü. Veel hard geluid."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hulp</span>?", o:["yardım","soru","zaman","yol"], c:0,
      e:"<b>de hulp</b> = yardım. Werkwoord: helpen = yardım etmek."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>ergens</span>?", o:["bir yerde","hiçbir yerde","her zaman","şimdi"], c:0,
      e:"<b>ergens</b> = bir yerde. Voorbeeld: <i>Mijn kaartje ligt ergens in mijn tas.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de vertraging</span>?", o:["gecikme","varış","hız","durak"], c:0,
      e:"<b>de vertraging</b> = gecikme. De trein komt later dan normaal."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>op tijd</span>?", o:["zamanında","geç","erken","asla"], c:0,
      e:"<b>op tijd</b> = zamanında. Niet te laat en niet te vroeg."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>duidelijk</span>?", o:["açık (net anlaşılır)","zor","yavaş","sessiz"], c:0,
      e:"<b>duidelijk</b> = açık / net. Je snapt het meteen. Voorbeeld: <i>Het bericht op het bord is duidelijk.</i>"},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ bericht</span>", o:["het bericht","de bericht","een berichten","die berichten"], c:0,
      e:"Het is <b>het bericht</b>. Dit woord krijgt 'het'."},
  ]},
  "4":{ title:"Reizen & OV-chipkaart", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opladen</span>?", o:["şarj etmek","kapatmak","satmak","kırmak"], c:0,
      e:"<b>opladen</b> = şarj etmek. Je laadt je OV-chipkaart of je telefoon op."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pinpas</span>?", o:["banka kartı","para","cüzdan","fatura"], c:0,
      e:"<b>de pinpas</b> = banka kartı. Hiermee betaal je in de winkel."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pincode</span>?", o:["pin kodu / şifre","adres","isim","numara"], c:0,
      e:"<b>de pincode</b> = pin kodu. De geheime cijfers van je pinpas."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>het scherm</span>?", o:["ekran","tuş","kart","ses"], c:0,
      e:"<b>het scherm</b> = ekran. Bijvoorbeeld het scherm van de automaat of je telefoon."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>veilig</span>?", o:["güvenli","tehlikeli","hızlı","yavaş"], c:0,
      e:"<b>veilig</b> = güvenli. Het tegenovergestelde is 'gevaarlijk' (tehlikeli)."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de knop</span>?", o:["düğme / tuş","kapı","yol","ekran"], c:0,
      e:"<b>de knop</b> = düğme/tuş. Je drukt op de knop."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>drukken op</span>?", o:["basmak","çekmek","tutmak","atmak"], c:0,
      e:"<b>drukken op</b> = basmak. Voorbeeld: <i>Druk op de groene knop.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>minimaal</span>?", o:["en az","en çok","bazen","hemen"], c:0,
      e:"<b>minimaal</b> = en az. Voorbeeld: <i>Je hebt minimaal 4 euro nodig.</i>"},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ scherm</span>", o:["het scherm","de scherm","een schermen","dat schermen"], c:0,
      e:"Het is <b>het scherm</b>. Dit woord krijgt 'het'."},
  ]},
  "5":{ title:"Contact met de buren", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>boos</span>?", o:["kızgın","mutlu","yorgun","üzgün"], c:0,
      e:"<b>boos</b> = kızgın. Voorbeeld: <i>De buurman is boos om het lawaai.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de gast</span>?", o:["misafir","komşu","aile","çocuk"], c:0,
      e:"<b>de gast</b> = misafir. Iemand die bij je op bezoek komt."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>moe</span>?", o:["yorgun","kızgın","mutlu","hasta"], c:0,
      e:"<b>moe</b> = yorgun. Voorbeeld: <i>Ik ben moe na het verhuizen.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>overmorgen</span>?", o:["öbür gün","dün","bugün","her gün"], c:0,
      e:"<b>overmorgen</b> = öbür gün (yarından sonraki gün). Vandaag → morgen → overmorgen."},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>hard</span> (sert / yüksek sesli)?", o:["zacht","stil","boos","moe"], c:0,
      e:"<b>hard</b> ↔ <b>zacht</b> (yumuşak / hafif). 'zacht' betekent ook: niet luid."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>stil</span>?", o:["sessiz","gürültülü","hızlı","güvenli"], c:0,
      e:"<b>stil</b> = sessiz. Het tegenovergestelde van lawaai."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de leeftijd</span>?", o:["yaş","isim","adres","boy"], c:0,
      e:"<b>de leeftijd</b> = yaş. Voorbeeld: <i>Wat is de leeftijd van je kind?</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de verjaardag</span>?", o:["doğum günü","davetiye","tatil","bayram"], c:0,
      e:"<b>de verjaardag</b> = doğum günü. Op je verjaardag word je een jaar ouder."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>oppassen</span>?", o:["göz kulak olmak","uyumak","oynamak","beklemek"], c:0,
      e:"<b>oppassen</b> = göz kulak olmak. Voorbeeld: <i>Ik pas op de kinderen van de buren.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>davetiye</span>?", o:["de uitnodiging","de verjaardag","het gesprek","de gast"], c:0,
      e:"davetiye = <b>de uitnodiging</b>. Je krijgt een uitnodiging voor een feest. 'de verjaardag' = doğum günü."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vieren</span>?", o:["kutlamak","çalışmak","beklemek","taşınmak"], c:0,
      e:"<b>vieren</b> = kutlamak. Voorbeeld: <i>Wij vieren mijn verjaardag met de buren.</i>"},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ gesprek</span> (konuşma)", o:["het gesprek","de gesprek","een gesprekken","die gesprekken"], c:0,
      e:"Het is <b>het gesprek</b>. Dit woord krijgt 'het'."},
  ]},
  "6":{ title:"Het huis beschrijven", sub:"Lees het Nederlandse woord en kies het goede antwoord. Türkçe woord staat erbij als hulp.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>modern</span>?", o:["modern / yeni tarz","eski","küçük","ucuz"], c:0,
      e:"<b>modern</b> = modern. Het tegenovergestelde is 'ouderwets' (eski)."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>ruim</span>?", o:["geniş / ferah","dar","karanlık","dolu"], c:0,
      e:"<b>ruim</b> = geniş/ferah. Er is veel plek. Voorbeeld: <i>Een ruime kamer.</i>"},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vierkant</span>?", o:["kare","yuvarlak","üçgen","uzun"], c:0,
      e:"<b>vierkant</b> = kare. Een vorm met vier gelijke kanten."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de meter</span>?", o:["metre","kilo","litre","saat"], c:0,
      e:"<b>de meter</b> = metre. Je meet lengte in meters. 100 cm = 1 meter."},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>laag</span> (alçak)?", o:["hoog","breed","rond","licht"], c:0,
      e:"<b>laag</b> = alçak, <b>hoog</b> = yüksek. Dat zijn tegenovergestelden."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hamer</span>?", o:["çekiç","testere","vida","merdiven"], c:0,
      e:"<b>de hamer</b> = çekiç. Gereedschap om te timmeren."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>licht</span>?", o:["hafif / aydınlık","ağır","karanlık","sıcak"], c:0,
      e:"<b>licht</b> heeft twee betekenissen: hafif (niet zwaar) én aydınlık/ışık. Tegenovergestelde van zwaar én van donker."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>rond</span>?", o:["yuvarlak","kare","düz","köşeli"], c:0,
      e:"<b>rond</b> = yuvarlak. Zoals een bal of een bord."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>breed</span>?", o:["geniş","dar","yüksek","kısa"], c:0,
      e:"<b>breed</b> = geniş. Het tegenovergestelde is 'smal' (dar)."},
  ]},
  "7":{ title:"Grote mix: les 1 t/m 6", sub:"Alle thema's uit les 1 t/m 6 door elkaar. Türkçe woord staat erbij als hulp. Elke keer in andere volgorde.", q:[
    {tag:"Woord → betekenis", t:"Wat betekent het woord <span class='m'>de buren</span>?", o:["komşular","misafir","aile","arkadaş"], c:0,
      e:"<b>de buren</b> = komşular. Dat zijn de mensen die naast je wonen."},
    {tag:"Werkwoord", t:"Welke zin is goed? <span class='m'>Gisteren ___ wij naar een nieuw huis. (verhuizen)</span>", o:["verhuisden","verhuizen","verhuis","verhuist"], c:0,
      e:"Verleden tijd: <b>verhuisden</b>. Nu = wij verhuizen, gisteren = wij verhuisden."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>verkopen</span>?", o:["satmak","almak","bakmak","aramak"], c:0,
      e:"<b>verkopen</b> = satmak. Het tegenovergestelde is 'kopen' (satın almak)."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>tweedehands</span>?", o:["ikinci el","yeni","pahalı","bedava"], c:0,
      e:"<b>tweedehands</b> = ikinci el. Iemand heeft het al gebruikt. Voorbeeld: <i>Ik koop een tweedehands bank.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>ayna</span>?", o:["de spiegel","het kleed","de hamer","de knop"], c:0,
      e:"ayna = <b>de spiegel</b>. In de spiegel zie je jezelf. 'het kleed' = halı, 'de hamer' = çekiç."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de vertraging</span>?", o:["gecikme","varış","hız","durak"], c:0,
      e:"<b>de vertraging</b> = gecikme. De trein komt later dan normaal."},
    {tag:"de of het", t:"Wat is goed? <span class='m'>___ bericht</span>", o:["het bericht","de bericht","een berichten","die berichten"], c:0,
      e:"Het is <b>het bericht</b>. Dit woord krijgt 'het'."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>opladen</span>?", o:["şarj etmek","kapatmak","satmak","kırmak"], c:0,
      e:"<b>opladen</b> = şarj etmek. Je laadt je OV-chipkaart of je telefoon op."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de pincode</span>?", o:["pin kodu / şifre","adres","isim","numara"], c:0,
      e:"<b>de pincode</b> = pin kodu. De geheime cijfers van je pinpas."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>veilig</span>?", o:["güvenli","tehlikeli","hızlı","yavaş"], c:0,
      e:"<b>veilig</b> = güvenli. Het tegenovergestelde is 'gevaarlijk' (tehlikeli)."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>boos</span>?", o:["kızgın","mutlu","yorgun","üzgün"], c:0,
      e:"<b>boos</b> = kızgın. Voorbeeld: <i>De buurman is boos om het lawaai.</i>"},
    {tag:"Betekenis → woord", t:"Welk woord betekent <span class='m'>davetiye</span>?", o:["de uitnodiging","de verjaardag","het gesprek","de gast"], c:0,
      e:"davetiye = <b>de uitnodiging</b>. Je krijgt een uitnodiging voor een feest. 'de verjaardag' = doğum günü."},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>hard</span> (sert / yüksek sesli)?", o:["zacht","stil","boos","moe"], c:0,
      e:"<b>hard</b> ↔ <b>zacht</b> (yumuşak / hafif). 'zacht' betekent ook: niet luid."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>vierkant</span>?", o:["kare","yuvarlak","üçgen","uzun"], c:0,
      e:"<b>vierkant</b> = kare. Een vorm met vier gelijke kanten."},
    {tag:"Tegenstelling", t:"Wat is het tegenovergestelde van <span class='m'>laag</span> (alçak)?", o:["hoog","breed","rond","licht"], c:0,
      e:"<b>laag</b> = alçak, <b>hoog</b> = yüksek. Dat zijn tegenovergestelden."},
    {tag:"Woord → betekenis", t:"Wat betekent <span class='m'>de hamer</span>?", o:["çekiç","testere","vida","merdiven"], c:0,
      e:"<b>de hamer</b> = çekiç. Gereedschap om te timmeren."},
  ]},
};
